"""Constants for loft surface creation."""

# Curve parameters
MIN_POSITIONS_FOR_CURVE = 2
MIN_POSITIONS_FOR_CUBIC_CURVE = 3
CURVE_DEGREE_LINEAR = 1
CURVE_DEGREE_CUBIC = 3
VALID_CURVE_DEGREES = [CURVE_DEGREE_LINEAR, CURVE_DEGREE_CUBIC]

# Output types
OUTPUT_NURBS_SURFACE = "nurbsSurface"
OUTPUT_MESH = "mesh"
VALID_OUTPUT_TYPES = [OUTPUT_NURBS_SURFACE, OUTPUT_MESH]

# Weight calculation methods (placeholder for future implementation)
WEIGHT_METHOD_LINEAR = "linear"
WEIGHT_METHOD_EASE = "ease"
WEIGHT_METHOD_STEP = "step"
VALID_WEIGHT_METHODS = [WEIGHT_METHOD_LINEAR, WEIGHT_METHOD_EASE, WEIGHT_METHOD_STEP]
