"""
Qt compatibility layer for PySide2/PySide6.

This module provides a unified import interface for Qt modules,
automatically handling the differences between PySide2 and PySide6.

Usage:
    from faketools.lib_ui.qt_compat import (
        QtCore, QtGui, QtWidgets,
        Qt, Signal, Slot
    )
"""

# Try to import PySide2 first (Maya 2022 and earlier)
try:
    from PySide2 import QtCore, QtGui, QtNetwork, QtOpenGL, QtSvg, QtWidgets
    from PySide2.QtCore import (
        QAbstractItemModel,
        QByteArray,  # noqa: F401
        QDateTime,
        QDir,
        QEvent,
        QFileInfo,
        QFileSystemWatcher,
        QItemSelectionModel,
        QMimeData,  # noqa: F401
        QModelIndex,
        QObject,
        QPoint,
        QPointF,
        QRect,
        QRectF,
        QSize,
        QSortFilterProxyModel,
        QStringListModel,
        Qt,
        QThread,
        QTimer,
        QUrl,
        Signal,
        Slot,
    )
    from PySide2.QtGui import (
        QBrush,
        QColor,
        QCursor,
        QDesktopServices,
        QDoubleValidator,
        QFont,
        QFontMetrics,
        QIcon,
        QImage,
        QIntValidator,
        QKeyEvent,
        QKeySequence,
        QPainter,
        QPainterPath,
        QPalette,
        QPen,
        QPixmap,
        QPolygon,
        QPolygonF,
        QRegExpValidator,
        QRegion,
        QResizeEvent,
        QStandardItem,
        QStandardItemModel,
        QSyntaxHighlighter,
        QTextCharFormat,
        QTextCursor,
        QTextDocument,
        QTransform,
        QValidator,
    )
    from PySide2.QtWidgets import (
        QAbstractItemView,
        QAction,
        QActionGroup,
        QApplication,
        QButtonGroup,
        QCheckBox,
        QColorDialog,
        QComboBox,
        QCompleter,
        QDialog,
        QDialogButtonBox,
        QDoubleSpinBox,
        QFileDialog,
        QFileSystemModel,
        QFontDialog,
        QFormLayout,
        QFrame,
        QGraphicsEllipseItem,
        QGraphicsItem,
        QGraphicsLineItem,
        QGraphicsOpacityEffect,
        QGraphicsPathItem,
        QGraphicsPolygonItem,
        QGraphicsRectItem,
        QGraphicsScene,
        QGraphicsTextItem,
        QGraphicsView,
        QGraphicsWidget,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QItemDelegate,
        QLabel,
        QLineEdit,
        QListView,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMenu,
        QMenuBar,
        QMessageBox,
        QPlainTextEdit,
        QProgressBar,
        QPushButton,
        QRadioButton,
        QRubberBand,
        QScrollArea,
        QShortcut,
        QSizePolicy,
        QSlider,
        QSpacerItem,
        QSpinBox,
        QSplitter,
        QStackedLayout,
        QStackedWidget,
        QStatusBar,
        QStyle,
        QStyledItemDelegate,
        QStyleOption,
        QStyleOptionButton,
        QStyleOptionComboBox,
        QStyleOptionTab,
        QStyleOptionViewItem,
        QStylePainter,
        QSystemTrayIcon,
        QTabBar,
        QTableView,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QTextEdit,
        QToolBar,
        QToolButton,
        QToolTip,
        QTreeView,
        QTreeWidget,
        QTreeWidgetItem,
        QVBoxLayout,
        QWidget,
    )

    # Version flag
    QT_VERSION = "PySide2"
    QT_VERSION_MAJOR = 5

    # Additional compatibility helpers
    def get_open_file_name(parent=None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "") -> tuple[str, str]:
        """Wrapper for QFileDialog.getOpenFileName with consistent signature."""
        return QFileDialog.getOpenFileName(parent, caption, directory, filter, selectedFilter)

    def get_save_file_name(parent=None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "") -> tuple[str, str]:
        """Wrapper for QFileDialog.getSaveFileName with consistent signature."""
        return QFileDialog.getSaveFileName(parent, caption, directory, filter, selectedFilter)

    import shiboken2 as shiboken

except ImportError:
    # Fall back to PySide6 (Maya 2023 and later)
    from PySide6 import QtCore, QtGui, QtNetwork, QtOpenGL, QtSvg, QtWidgets
    from PySide6.QtCore import (
        QAbstractItemModel,
        QByteArray,  # noqa: F401
        QDateTime,
        QDir,
        QEvent,
        QFileInfo,
        QFileSystemWatcher,
        QItemSelectionModel,
        QMimeData,  # noqa: F401
        QModelIndex,
        QObject,
        QPoint,
        QPointF,
        QRect,
        QRectF,
        QSize,
        QSortFilterProxyModel,
        QStringListModel,
        Qt,
        QThread,
        QTimer,
        QUrl,
        Signal,
        Slot,
    )
    from PySide6.QtGui import (
        QAction,
        QActionGroup,
        QBrush,
        QColor,
        QCursor,
        QDesktopServices,
        QDoubleValidator,
        QFont,
        QFontMetrics,
        QIcon,
        QImage,
        QIntValidator,
        QKeyEvent,
        QKeySequence,
        QPainter,
        QPainterPath,
        QPalette,
        QPen,
        QPixmap,
        QPolygon,
        QPolygonF,
        QRegion,
        QRegularExpressionValidator as QRegExpValidator,
        QResizeEvent,
        QShortcut,
        QStandardItem,
        QStandardItemModel,
        QSyntaxHighlighter,
        QTextCharFormat,
        QTextCursor,
        QTextDocument,
        QTransform,
        QValidator,
    )
    from PySide6.QtWidgets import (
        QAbstractItemView,
        QApplication,
        QButtonGroup,
        QCheckBox,
        QColorDialog,
        QComboBox,
        QCompleter,
        QDialog,
        QDialogButtonBox,
        QDoubleSpinBox,
        QFileDialog,
        QFileSystemModel,
        QFontDialog,
        QFormLayout,
        QFrame,
        QGraphicsEllipseItem,
        QGraphicsItem,
        QGraphicsLineItem,
        QGraphicsOpacityEffect,
        QGraphicsPathItem,
        QGraphicsPolygonItem,
        QGraphicsRectItem,
        QGraphicsScene,
        QGraphicsTextItem,
        QGraphicsView,
        QGraphicsWidget,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QItemDelegate,
        QLabel,
        QLineEdit,
        QListView,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMenu,
        QMenuBar,
        QMessageBox,
        QPlainTextEdit,
        QProgressBar,
        QPushButton,
        QRadioButton,
        QRubberBand,
        QScrollArea,
        QSizePolicy,
        QSlider,
        QSpacerItem,
        QSpinBox,
        QSplitter,
        QStackedLayout,
        QStackedWidget,
        QStatusBar,
        QStyle,
        QStyledItemDelegate,
        QStyleOption,
        QStyleOptionButton,
        QStyleOptionComboBox,
        QStyleOptionTab,
        QStyleOptionViewItem,
        QStylePainter,
        QSystemTrayIcon,
        QTabBar,
        QTableView,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QTextEdit,
        QToolBar,
        QToolButton,
        QToolTip,
        QTreeView,
        QTreeWidget,
        QTreeWidgetItem,
        QVBoxLayout,
        QWidget,
    )

    # Version flag
    QT_VERSION = "PySide6"
    QT_VERSION_MAJOR = 6

    # Additional compatibility helpers
    def get_open_file_name(parent=None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "") -> tuple[str, str]:
        """Wrapper for QFileDialog.getOpenFileName with consistent signature."""
        result = QFileDialog.getOpenFileName(parent, caption, directory, filter, selectedFilter)
        return result[0], result[1]

    def get_save_file_name(parent=None, caption: str = "", directory: str = "", filter: str = "", selectedFilter: str = "") -> tuple[str, str]:
        """Wrapper for QFileDialog.getSaveFileName with consistent signature."""
        result = QFileDialog.getSaveFileName(parent, caption, directory, filter, selectedFilter)
        return result[0], result[1]

    import shiboken6 as shiboken


# Common aliases for convenience
QT_BINDING = QT_VERSION


def is_pyside2() -> bool:
    """Check if using PySide2."""
    return QT_VERSION == "PySide2"


def is_pyside6() -> bool:
    """Check if using PySide6."""
    return QT_VERSION == "PySide6"


# Export all for easy star import if needed
__all__ = [
    # Core modules
    "QtCore",
    "QtGui",
    "QtWidgets",
    "QtOpenGL",
    "QtSvg",
    "QtNetwork",
    # Common classes
    "Qt",
    "Signal",
    "Slot",
    "QObject",
    "QEvent",
    "QTimer",
    "QThread",
    "QSize",
    "QPoint",
    "QPointF",
    "QRect",
    "QRectF",
    "QDir",
    "QFileInfo",
    "QDateTime",
    "QModelIndex",
    "QFileSystemWatcher",
    "QUrl",
    # GUI classes
    "QDesktopServices",
    "QFont",
    "QFontMetrics",
    "QIcon",
    "QPalette",
    "QPixmap",
    "QImage",
    "QColor",
    "QCursor",
    "QKeySequence",
    "QKeyEvent",
    "QResizeEvent",
    "QValidator",
    "QIntValidator",
    "QDoubleValidator",
    "QRegExpValidator",
    "QPainter",
    "QPainterPath",
    "QPen",
    "QBrush",
    "QPolygon",
    "QPolygonF",
    "QRegion",
    "QTransform",
    "QSyntaxHighlighter",
    "QTextCharFormat",
    "QTextCursor",
    "QTextDocument",
    "QShortcut",
    # Widget classes
    "QApplication",
    "QMainWindow",
    "QDialog",
    "QDialogButtonBox",
    "QWidget",
    "QHBoxLayout",
    "QVBoxLayout",
    "QGridLayout",
    "QFormLayout",
    "QStackedLayout",
    "QLabel",
    "QPushButton",
    "QLineEdit",
    "QTextEdit",
    "QPlainTextEdit",
    "QCheckBox",
    "QRadioButton",
    "QComboBox",
    "QSpinBox",
    "QDoubleSpinBox",
    "QSlider",
    "QProgressBar",
    "QGroupBox",
    "QTabWidget",
    "QTabBar",
    "QStackedWidget",
    "QListWidget",
    "QListWidgetItem",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QTableWidget",
    "QTableWidgetItem",
    "QListView",
    "QTreeView",
    "QTableView",
    "QHeaderView",
    "QSplitter",
    "QScrollArea",
    "QToolBar",
    "QStatusBar",
    "QMenuBar",
    "QMenu",
    "QAction",
    "QActionGroup",
    "QToolButton",
    "QToolTip",
    "QButtonGroup",
    "QAbstractItemView",
    "QAbstractItemModel",
    "QStandardItemModel",
    "QStandardItem",
    "QStringListModel",
    "QSortFilterProxyModel",
    "QItemSelectionModel",
    "QItemDelegate",
    "QStyledItemDelegate",
    "QStyleOptionViewItem",
    "QFileSystemModel",
    "QFileDialog",
    "QColorDialog",
    "QFontDialog",
    "QMessageBox",
    "QInputDialog",
    "QGraphicsScene",
    "QGraphicsView",
    "QGraphicsItem",
    "QGraphicsEllipseItem",
    "QGraphicsLineItem",
    "QGraphicsOpacityEffect",
    "QGraphicsPathItem",
    "QGraphicsPolygonItem",
    "QGraphicsRectItem",
    "QGraphicsTextItem",
    "QGraphicsWidget",
    "QRubberBand",
    "QSizePolicy",
    "QSpacerItem",
    "QCompleter",
    "QSystemTrayIcon",
    "QStyle",
    "QStyleOption",
    "QStyleOptionButton",
    "QStyleOptionComboBox",
    "QStyleOptionTab",
    "QStylePainter",
    "QFrame",
    # Version info
    "QT_VERSION",
    "QT_VERSION_MAJOR",
    "QT_BINDING",
    # Helper functions
    "is_pyside2",
    "is_pyside6",
    "get_open_file_name",
    "get_save_file_name",
    # "shiboken"
    "shiboken",
]
