"""Constants for curve surface creation."""

# Curve parameters
MIN_POSITIONS_FOR_CURVE = 2
MIN_POSITIONS_FOR_CUBIC_CURVE = 3
CURVE_DEGREE_LINEAR = 1
CURVE_DEGREE_CUBIC = 3
VALID_CURVE_DEGREES = [CURVE_DEGREE_LINEAR, CURVE_DEGREE_CUBIC]

# Object types
OBJECT_TYPE_CURVE = "nurbsCurve"
OBJECT_TYPE_MESH = "mesh"
OBJECT_TYPE_SURFACE = "nurbsSurface"
VALID_OBJECT_TYPES = [OBJECT_TYPE_CURVE, OBJECT_TYPE_MESH, OBJECT_TYPE_SURFACE]

# Surface axis types
AXIS_X = "x"
AXIS_Y = "y"
AXIS_Z = "z"
AXIS_NORMAL = "normal"
AXIS_BINORMAL = "binormal"
VALID_SURFACE_AXES = [AXIS_X, AXIS_Y, AXIS_Z, AXIS_NORMAL, AXIS_BINORMAL]

# Weight calculation methods
METHOD_LINEAR = "linear"
METHOD_EASE = "ease"
METHOD_STEP = "step"
VALID_WEIGHT_METHODS = [METHOD_LINEAR, METHOD_EASE, METHOD_STEP]

# Ease types
EASE_IN = "in"
EASE_OUT = "out"
EASE_INOUT = "inout"
VALID_EASE_TYPES = [EASE_IN, EASE_OUT, EASE_INOUT]
