"""Auto-generated stub for maya.api.OpenMayaAnim. Do not edit."""

from typing import Any

class MAnimControl:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def animationEndTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def animationStartTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def autoKeyMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def currentTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def globalInTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def globalOutTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def isPlaying(self, *args: Any, **kwargs: Any) -> Any: ...
    def isScrubbing(self, *args: Any, **kwargs: Any) -> Any: ...
    kPlaybackLoop: Any = ...
    kPlaybackOnce: Any = ...
    kPlaybackOscillate: Any = ...
    kPlaybackViewActive: Any = ...
    kPlaybackViewAll: Any = ...
    def maxTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def minTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def playBackward(self, *args: Any, **kwargs: Any) -> Any: ...
    def playForward(self, *args: Any, **kwargs: Any) -> Any: ...
    def playbackBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def playbackMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def playbackSpeed(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimationEndTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimationStartEndTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimationStartTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAutoKeyMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setCurrentTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGlobalInTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGlobalOutTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinMaxTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPlaybackBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPlaybackMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPlaybackSpeed(self, *args: Any, **kwargs: Any) -> Any: ...
    def setViewMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeightedTangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def weightedTangents(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimCurveChange:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def redoIt(self, *args: Any, **kwargs: Any) -> Any: ...
    def undoIt(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimCurveClipboard:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def clipboardItems(self, *args: Any, **kwargs: Any) -> Any: ...
    endTime: Any = ...
    endUnitlessInput: Any = ...
    isEmpty: Any = ...
    def set(self, *args: Any, **kwargs: Any) -> Any: ...
    startTime: Any = ...
    startUnitlessInput: Any = ...
    theAPIClipboard: Any = ...

class MAnimCurveClipboardItem:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    animCurve: Any = ...
    def animCurveType(self, *args: Any, **kwargs: Any) -> Any: ...
    fullAttributeName: Any = ...
    def getAddressingInfo(self, *args: Any, **kwargs: Any) -> Any: ...
    leafAttributeName: Any = ...
    nodeName: Any = ...
    def setAddressingInfo(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimCurve(self, *args: Any, **kwargs: Any) -> Any: ...
    def setNameInfo(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimCurveClipboardItemArray:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLength(self, *args: Any, **kwargs: Any) -> Any: ...
    sizeIncrement: Any = ...

class MAnimMessage:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAnimCurveEditedCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAnimKeyframeEditCheckCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAnimKeyframeEditedCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addDisableImplicitControlCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addNodeAnimKeyframeEditedCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addPostBakeResultsCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addPreBakeResultsCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def currentCallbackId(self, *args: Any, **kwargs: Any) -> Any: ...
    def flushAnimKeyframeEditedCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    kDefaultAction: Any = ...
    kDoAction: Any = ...
    kDoNotDoAction: Any = ...
    def nodeCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimUtil:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def createAnimCurve(self, *args: Any, **kwargs: Any) -> Any: ...
    def findActiveAnimationLayer(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimCurve(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimatablePlugs(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimatedPlugs(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimationLayers(self, *args: Any, **kwargs: Any) -> Any: ...
    def findBlendNodeInputPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def findConstraint(self, *args: Any, **kwargs: Any) -> Any: ...
    def findSetDrivenKeyAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def isAnimated(self, *args: Any, **kwargs: Any) -> Any: ...
    kActiveLayer: Any = ...
    kAffectingLayers: Any = ...
    kAffectingUnlockedLayers: Any = ...
    kAllLayers: Any = ...
    kAllUnlockedLayers: Any = ...

class MFnAnimCurve:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def addKey(self, *args: Any, **kwargs: Any) -> Any: ...
    def addKeys(self, *args: Any, **kwargs: Any) -> Any: ...
    def addKeysWithTangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    animCurveType: Any = ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    def evaluate(self, *args: Any, **kwargs: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findClosest(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTangentAngleWeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTangentXY(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def inTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def input(self, *args: Any, **kwargs: Any) -> Any: ...
    def insertKey(self, *args: Any, **kwargs: Any) -> Any: ...
    def isBreakdown(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    isStatic: Any = ...
    isTimeInput: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    isUnitlessInput: Any = ...
    isWeighted: Any = ...
    kAnimCurveTA: Any = ...
    kAnimCurveTL: Any = ...
    kAnimCurveTT: Any = ...
    kAnimCurveTU: Any = ...
    kAnimCurveUA: Any = ...
    kAnimCurveUL: Any = ...
    kAnimCurveUT: Any = ...
    kAnimCurveUU: Any = ...
    kAnimCurveUnknown: Any = ...
    kConstant: Any = ...
    kCycle: Any = ...
    kCycleRelative: Any = ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLinear: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kOscillate: Any = ...
    kTangentAuto: Any = ...
    kTangentAutoCustom: Any = ...
    kTangentAutoEase: Any = ...
    kTangentAutoMix: Any = ...
    kTangentClamped: Any = ...
    kTangentCustomEnd: Any = ...
    kTangentCustomStart: Any = ...
    kTangentFast: Any = ...
    kTangentFixed: Any = ...
    kTangentFlat: Any = ...
    kTangentGlobal: Any = ...
    kTangentLinear: Any = ...
    kTangentPlateau: Any = ...
    kTangentShared1: Any = ...
    kTangentShared2: Any = ...
    kTangentShared3: Any = ...
    kTangentShared4: Any = ...
    kTangentShared5: Any = ...
    kTangentShared6: Any = ...
    kTangentShared7: Any = ...
    kTangentShared8: Any = ...
    kTangentSlow: Any = ...
    kTangentSmooth: Any = ...
    kTangentStep: Any = ...
    kTangentStepNext: Any = ...
    kTangentTypeCount: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    numKeys: Any = ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    postInfinityType: Any = ...
    preInfinityType: Any = ...
    def quaternionW(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAngle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setInTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setInput(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIsBreakdown(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIsWeighted(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setOutTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPostInfinityType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPreInfinityType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setQuaternionW(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTangent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTangentTypes(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTangentsLocked(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def setValue(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeightsLocked(self, *args: Any, **kwargs: Any) -> Any: ...
    def tangentsLocked(self, *args: Any, **kwargs: Any) -> Any: ...
    def timedAnimCurveTypeForPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def unitlessAnimCurveTypeForPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def value(self, *args: Any, **kwargs: Any) -> Any: ...
    def weightsLocked(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnGeometryFilter:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    deformerSet: Any = ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    envelope: Any = ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getComponentAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getInputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getOutputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPathAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def groupIdAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForGroupId(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputShape(self, *args: Any, **kwargs: Any) -> Any: ...
    def inputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    def numOutputConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnIkJoint:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addChild(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def balanceTransformation(self, *args: Any, **kwargs: Any) -> Any: ...
    boundingBox: Any = ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def child(self, *args: Any, **kwargs: Any) -> Any: ...
    def childCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearRestPosition(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def dagPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def dagRoot(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def degreesOfFreedom(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    def duplicate(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableLimit(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def fullPathName(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAllPaths(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnectedSetsAndMembers(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasChild(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasParent(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def hikJointName(self, *args: Any, **kwargs: Any) -> Any: ...
    inModel: Any = ...
    inUnderWorld: Any = ...
    def instanceCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def isChildOf(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isInstanceable: Any = ...
    def isInstanced(self, *args: Any, **kwargs: Any) -> Any: ...
    def isInstancedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isIntermediateObject: Any = ...
    def isLimited(self, *args: Any, **kwargs: Any) -> Any: ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def isParentOf(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLocalDynamicAttr: Any = ...
    kNextPos: Any = ...
    kNormalAttr: Any = ...
    kRotateMaxX: Any = ...
    kRotateMaxY: Any = ...
    kRotateMaxZ: Any = ...
    kRotateMinX: Any = ...
    kRotateMinY: Any = ...
    kRotateMinZ: Any = ...
    kScaleMaxX: Any = ...
    kScaleMaxY: Any = ...
    kScaleMaxZ: Any = ...
    kScaleMinX: Any = ...
    kScaleMinY: Any = ...
    kScaleMinZ: Any = ...
    kShearMaxXY: Any = ...
    kShearMaxXZ: Any = ...
    kShearMaxYZ: Any = ...
    kShearMinXY: Any = ...
    kShearMinXZ: Any = ...
    kShearMinYZ: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    kTranslateMaxX: Any = ...
    kTranslateMaxY: Any = ...
    kTranslateMaxZ: Any = ...
    kTranslateMinX: Any = ...
    kTranslateMinY: Any = ...
    kTranslateMinZ: Any = ...
    def limitValue(self, *args: Any, **kwargs: Any) -> Any: ...
    def maxRotateDampXRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def maxRotateDampXStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def maxRotateDampYRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def maxRotateDampYStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def maxRotateDampZRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def maxRotateDampZStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def minRotateDampXRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def minRotateDampXStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def minRotateDampYRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def minRotateDampYStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def minRotateDampZRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def minRotateDampZStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    objectColor: Any = ...
    objectColorRGB: Any = ...
    objectColorType: Any = ...
    def orientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def orientationComponents(self, *args: Any, **kwargs: Any) -> Any: ...
    def parent(self, *args: Any, **kwargs: Any) -> Any: ...
    def parentCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def partialPathName(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def preferredAngle(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeChild(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeChildAt(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def resetFromRestPosition(self, *args: Any, **kwargs: Any) -> Any: ...
    def resetTransformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def restPosition(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotateBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotateByComponents(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotateOrientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotatePivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotatePivotTranslation(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotationComponents(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotationOrder(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def scaleBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def scaleOrientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def scalePivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def scalePivotTranslation(self, *args: Any, **kwargs: Any) -> Any: ...
    def segmentScale(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDegreesOfFreedom(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLimit(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxRotateDampXRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxRotateDampXStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxRotateDampYRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxRotateDampYStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxRotateDampZRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxRotateDampZStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinRotateDampXRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinRotateDampXStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinRotateDampYRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinRotateDampYStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinRotateDampZRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinRotateDampZStrength(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setOrientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPreferredAngle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRestPosition(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRotateOrientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRotatePivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRotatePivotTranslation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRotationComponents(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRotationOrder(self, *args: Any, **kwargs: Any) -> Any: ...
    def setScale(self, *args: Any, **kwargs: Any) -> Any: ...
    def setScaleOrientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setScalePivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def setScalePivotTranslation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setSegmentScale(self, *args: Any, **kwargs: Any) -> Any: ...
    def setShear(self, *args: Any, **kwargs: Any) -> Any: ...
    def setStiffness(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTransformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTranslation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def shear(self, *args: Any, **kwargs: Any) -> Any: ...
    def shearBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def stiffness(self, *args: Any, **kwargs: Any) -> Any: ...
    def transformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def transformationMatrix(self, *args: Any, **kwargs: Any) -> Any: ...
    def translateBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def translation(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    useObjectColor: Any = ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnSkinCluster:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    deformerSet: Any = ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    envelope: Any = ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getBlendWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def getComponentAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getInputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getOutputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPathAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPointsAffectedByInfluence(self, *args: Any, **kwargs: Any) -> Any: ...
    def getWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def groupIdAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForGroupId(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForInfluenceObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputShape(self, *args: Any, **kwargs: Any) -> Any: ...
    def influenceObjects(self, *args: Any, **kwargs: Any) -> Any: ...
    def inputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    def numOutputConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setBlendWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnWeightGeometryFilter:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    deformerSet: Any = ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    envelope: Any = ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getComponentAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEnvelopeWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getInputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getOutputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPathAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getWeightPlugStrings(self, *args: Any, **kwargs: Any) -> Any: ...
    def getWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def groupIdAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForGroupId(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputShape(self, *args: Any, **kwargs: Any) -> Any: ...
    def inputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    def numOutputConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def weightPlugStrings(self, *args: Any, **kwargs: Any) -> Any: ...

key: Any = ...

maya: Any = ...

ourdict: Any = ...

py2dict: Any = ...

val: Any = ...
