"""Auto-generated stub for maya.api.OpenMayaRender. Do not edit."""

from typing import Any

class MAttributeParameterMapping:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def allowConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def allowRename(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeName(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterName(self, *args: Any, **kwargs: Any) -> Any: ...
    def resolvedParameterName(self, *args: Any, **kwargs: Any) -> Any: ...

class MAttributeParameterMappingList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def findByAttributeName(self, *args: Any, **kwargs: Any) -> Any: ...
    def findByParameterName(self, *args: Any, **kwargs: Any) -> Any: ...

class MBlendState:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def desc(self, *args: Any, **kwargs: Any) -> Any: ...
    kAdd: Any = ...
    kAlphaChannel: Any = ...
    kBlendFactor: Any = ...
    kBlueChannel: Any = ...
    kBothInvSourceAlpha: Any = ...
    kBothSourceAlpha: Any = ...
    kDestinationAlpha: Any = ...
    kDestinationColor: Any = ...
    kGreenChannel: Any = ...
    kInvBlendFactor: Any = ...
    kInvDestinationAlpha: Any = ...
    kInvDestinationColor: Any = ...
    kInvSourceAlpha: Any = ...
    kInvSourceColor: Any = ...
    kMax: Any = ...
    kMaxTargets: Any = ...
    kMin: Any = ...
    kNoChannels: Any = ...
    kOne: Any = ...
    kRGBAChannels: Any = ...
    kRGBChannels: Any = ...
    kRedChannel: Any = ...
    kReverseSubtract: Any = ...
    kSourceAlpha: Any = ...
    kSourceAlphaSat: Any = ...
    kSourceColor: Any = ...
    kSubtract: Any = ...
    kZero: Any = ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...

class MBlendStateDesc:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    alphaToCoverageEnable: Any = ...
    blendFactor: Any = ...
    independentBlendEnable: Any = ...
    multiSampleMask: Any = ...
    def setDefaults(self, *args: Any, **kwargs: Any) -> Any: ...
    targetBlends: Any = ...

class MCameraOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    mCameraPath: Any = ...
    mFarClippingPlane: Any = ...
    mHiddenCameraList: Any = ...
    mNearClippingPlane: Any = ...
    mProjectionMatrix: Any = ...
    mUseFarClippingPlane: Any = ...
    mUseHiddenCameraList: Any = ...
    mUseNearClippingPlane: Any = ...
    mUseProjectionMatrix: Any = ...
    mUseViewMatrix: Any = ...
    mViewMatrix: Any = ...

class MClearOperation:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearColor(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearColor2(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearDepth(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearGradient(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearStencil(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    kClear: Any = ...
    kClearAll: Any = ...
    kClearColor: Any = ...
    kClearDepth: Any = ...
    kClearNone: Any = ...
    kClearStencil: Any = ...
    kHUDRender: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kSceneRender: Any = ...
    kUserDefined: Any = ...
    def mask(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def overridesColors(self, *args: Any, **kwargs: Any) -> Any: ...
    def setClearColor(self, *args: Any, **kwargs: Any) -> Any: ...
    def setClearColor2(self, *args: Any, **kwargs: Any) -> Any: ...
    def setClearDepth(self, *args: Any, **kwargs: Any) -> Any: ...
    def setClearGradient(self, *args: Any, **kwargs: Any) -> Any: ...
    def setClearStencil(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMask(self, *args: Any, **kwargs: Any) -> Any: ...
    def setOverridesColors(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MColorManagementUtilities:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def getColorTransformCacheIdForInputSpace(self, *args: Any, **kwargs: Any) -> Any: ...
    def getColorTransformCacheIdForOutputTransform(self, *args: Any, **kwargs: Any) -> Any: ...
    def getColorTransformData(self, *args: Any, **kwargs: Any) -> Any: ...
    def isColorManagementAvailable(self, *args: Any, **kwargs: Any) -> Any: ...
    def isColorManagementEnabled(self, *args: Any, **kwargs: Any) -> Any: ...

class MComponentDataIndexing:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def componentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def indices(self, *args: Any, **kwargs: Any) -> Any: ...
    kFaceVertex: Any = ...
    def setComponentType(self, *args: Any, **kwargs: Any) -> Any: ...

class MComponentDataIndexingList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class MDepthNormalizationDescription:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    fDepthBias: Any = ...
    fDepthScale: Any = ...
    fFarClipDistance: Any = ...
    fNearClipDistance: Any = ...

class MDepthStencilState:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def desc(self, *args: Any, **kwargs: Any) -> Any: ...
    kDecrementStencil: Any = ...
    kDecrementStencilSat: Any = ...
    kIncrementStencil: Any = ...
    kIncrementStencilSat: Any = ...
    kInvertStencil: Any = ...
    kKeepStencil: Any = ...
    kReplaceStencil: Any = ...
    kZeroStencil: Any = ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...

class MDepthStencilStateDesc:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    backFace: Any = ...
    depthEnable: Any = ...
    depthFunc: Any = ...
    depthWriteEnable: Any = ...
    frontFace: Any = ...
    def setDefaults(self, *args: Any, **kwargs: Any) -> Any: ...
    stencilEnable: Any = ...
    stencilReadMask: Any = ...
    stencilReferenceVal: Any = ...
    stencilWriteMask: Any = ...

class MDrawContext:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def classificationExclusions(self, *args: Any, **kwargs: Any) -> Any: ...
    def copyCurrentColorRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def copyCurrentColorRenderTargetToTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def copyCurrentDepthRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def copyCurrentDepthRenderTargetToTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def getBackgroundParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCurrentCameraPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCurrentColorRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCurrentDepthRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDOFParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDepthRange(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDisplayStyle(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEnvironmentParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFrameStamp(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFrustumBox(self, *args: Any, **kwargs: Any) -> Any: ...
    def getGlobalLineWidth(self, *args: Any, **kwargs: Any) -> Any: ...
    def getHwFogParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLightInformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLightLimit(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLightParameterInformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLightingMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def getMatrix(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPassContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPostEffectEnabled(self, *args: Any, **kwargs: Any) -> Any: ...
    def getRenderOverrideInformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def getRenderTargetSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def getSceneBox(self, *args: Any, **kwargs: Any) -> Any: ...
    def getStateManager(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTransparencyAlgorithm(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTuple(self, *args: Any, **kwargs: Any) -> Any: ...
    def getViewportDimensions(self, *args: Any, **kwargs: Any) -> Any: ...
    def inUserInteraction(self, *args: Any, **kwargs: Any) -> Any: ...
    k2dViewport: Any = ...
    k3dViewport: Any = ...
    kAmbientLight: Any = ...
    kAmbientOcclusion: Any = ...
    kAntiAliasing: Any = ...
    kBackfaceCulling: Any = ...
    kBoundingBox: Any = ...
    kCustomLights: Any = ...
    kDefaultMaterial: Any = ...
    kDepthOfField: Any = ...
    kDepthPeeling: Any = ...
    kExcludeAll: Any = ...
    kExcludeCVs: Any = ...
    kExcludeCameras: Any = ...
    kExcludeClipGhosts: Any = ...
    kExcludeControllers: Any = ...
    kExcludeDeformers: Any = ...
    kExcludeDimensions: Any = ...
    kExcludeDynamicConstraints: Any = ...
    kExcludeDynamics: Any = ...
    kExcludeFluids: Any = ...
    kExcludeFollicles: Any = ...
    kExcludeGreasePencils: Any = ...
    kExcludeGrid: Any = ...
    kExcludeHUD: Any = ...
    kExcludeHairSystems: Any = ...
    kExcludeHoldOuts: Any = ...
    kExcludeHulls: Any = ...
    kExcludeIkHandles: Any = ...
    kExcludeImagePlane: Any = ...
    kExcludeJoints: Any = ...
    kExcludeLights: Any = ...
    kExcludeLocators: Any = ...
    kExcludeManipulators: Any = ...
    kExcludeMeshes: Any = ...
    kExcludeMotionTrails: Any = ...
    kExcludeNCloths: Any = ...
    kExcludeNParticles: Any = ...
    kExcludeNRigids: Any = ...
    kExcludeNone: Any = ...
    kExcludeNurbsCurves: Any = ...
    kExcludeNurbsSurfaces: Any = ...
    kExcludeParticleInstancers: Any = ...
    kExcludePivots: Any = ...
    kExcludePlanes: Any = ...
    kExcludePluginShapes: Any = ...
    kExcludeSelectHandles: Any = ...
    kExcludeStrokes: Any = ...
    kExcludeSubdivSurfaces: Any = ...
    kExcludeTextures: Any = ...
    kFilteredIgnoreLightLimit: Any = ...
    kFilteredToLightLimit: Any = ...
    kFlatShaded: Any = ...
    kFogExp: Any = ...
    kFogExp2: Any = ...
    kFogLinear: Any = ...
    kGammaCorrection: Any = ...
    kGouraudShaded: Any = ...
    kImage: Any = ...
    kLightDefault: Any = ...
    kMotionBlur: Any = ...
    kNoLighting: Any = ...
    kObjectSorting: Any = ...
    kProjectionInverseMtx: Any = ...
    kProjectionMtx: Any = ...
    kProjectionTranposeMtx: Any = ...
    kProjectionTranspInverseMtx: Any = ...
    kSceneLights: Any = ...
    kSelectedLights: Any = ...
    kShadeActiveOnly: Any = ...
    kSmoothWireframe: Any = ...
    kTextured: Any = ...
    kTwoSidedLighting: Any = ...
    kUnsorted: Any = ...
    kViewColorTransformEnabled: Any = ...
    kViewDirection: Any = ...
    kViewFarClipValue: Any = ...
    kViewInverseMtx: Any = ...
    kViewMtx: Any = ...
    kViewNearClipValue: Any = ...
    kViewPosition: Any = ...
    kViewProjInverseMtx: Any = ...
    kViewProjMtx: Any = ...
    kViewProjTranposeMtx: Any = ...
    kViewProjTranspInverseMtx: Any = ...
    kViewRight: Any = ...
    kViewTranspInverseMtx: Any = ...
    kViewTransposeMtx: Any = ...
    kViewUnnormalizedFarClipValue: Any = ...
    kViewUnnormlizedNearClipValue: Any = ...
    kViewUp: Any = ...
    kViewportPixelSize: Any = ...
    kWeightedAverage: Any = ...
    kWireFrame: Any = ...
    kWireFrameOnShadedNone: Any = ...
    kWireFrameOnShadedReduced: Any = ...
    kWireframeOnShadedFull: Any = ...
    kWorldInverseMtx: Any = ...
    kWorldMtx: Any = ...
    kWorldTranspInverseMtx: Any = ...
    kWorldTransposeMtx: Any = ...
    kWorldViewInverseMtx: Any = ...
    kWorldViewMtx: Any = ...
    kWorldViewProjInverseMtx: Any = ...
    kWorldViewProjMtx: Any = ...
    kWorldViewProjTranspInverseMtx: Any = ...
    kWorldViewProjTransposeMtx: Any = ...
    kWorldViewTranspInverseMtx: Any = ...
    kWorldViewTransposeMtx: Any = ...
    kXray: Any = ...
    kXrayActiveComponents: Any = ...
    kXrayJoint: Any = ...
    def numberOfActiveLights(self, *args: Any, **kwargs: Any) -> Any: ...
    def objectTypeExclusions(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderingDestination(self, *args: Any, **kwargs: Any) -> Any: ...
    def semanticToMatrixType(self, *args: Any, **kwargs: Any) -> Any: ...
    def semanticToTupleType(self, *args: Any, **kwargs: Any) -> Any: ...
    def shadeTemplates(self, *args: Any, **kwargs: Any) -> Any: ...
    def userChangingViewContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewDirectionAlongNegZ(self, *args: Any, **kwargs: Any) -> Any: ...
    def wireOnShadedMode(self, *args: Any, **kwargs: Any) -> Any: ...

class MDrawRegistry:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterComponentConverter(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterDrawOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterGeometryOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterImagePlaneOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterIndexBufferMutator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterPrimitiveGenerator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterShaderOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterShadingNodeOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterSubSceneOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterSurfaceShadingNodeOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterVertexBufferGenerator(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterVertexBufferMutator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerComponentConverter(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerDrawOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerGeometryOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerImagePlaneOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerIndexBufferMutator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerPrimitiveGenerator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerShaderOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerShadingNodeOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerSubSceneOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerSurfaceShadingNodeOverrideCreator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerVertexBufferGenerator(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerVertexBufferMutator(self, *args: Any, **kwargs: Any) -> Any: ...

class MFragmentManager:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAutomaticShaderStageInput(self, *args: Any, **kwargs: Any) -> Any: ...
    def addDomainShaderInputNameMapping(self, *args: Any, **kwargs: Any) -> Any: ...
    def addFragmentGraphFromBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def addFragmentGraphFromFile(self, *args: Any, **kwargs: Any) -> Any: ...
    def addFragmentPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def addShadeFragmentFromBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def addShadeFragmentFromFile(self, *args: Any, **kwargs: Any) -> Any: ...
    def findDomainShaderInputName(self, *args: Any, **kwargs: Any) -> Any: ...
    def fragmentList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEffectOutputDirectory(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFragmentXML(self, *args: Any, **kwargs: Any) -> Any: ...
    def getIntermediateGraphOutputDirectory(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasFragment(self, *args: Any, **kwargs: Any) -> Any: ...
    kDomainShader: Any = ...
    kGeometryShader: Any = ...
    kHullConstantShader: Any = ...
    kHullShader: Any = ...
    kPixelShader: Any = ...
    kVertexShader: Any = ...
    def removeAutomaticShaderStageInput(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeDomainShaderInputNameMapping(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeFragment(self, *args: Any, **kwargs: Any) -> Any: ...
    def setEffectOutputDirectory(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIntermediateGraphOutputDirectory(self, *args: Any, **kwargs: Any) -> Any: ...

class MFrameContext:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def classificationExclusions(self, *args: Any, **kwargs: Any) -> Any: ...
    def getBackgroundParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCurrentCameraPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCurrentColorRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCurrentDepthRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDOFParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDisplayStyle(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEnvironmentParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getGlobalLineWidth(self, *args: Any, **kwargs: Any) -> Any: ...
    def getHwFogParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLightLimit(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLightingMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def getMatrix(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPostEffectEnabled(self, *args: Any, **kwargs: Any) -> Any: ...
    def getRenderOverrideInformation(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTransparencyAlgorithm(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTuple(self, *args: Any, **kwargs: Any) -> Any: ...
    def getViewportDimensions(self, *args: Any, **kwargs: Any) -> Any: ...
    def inUserInteraction(self, *args: Any, **kwargs: Any) -> Any: ...
    k2dViewport: Any = ...
    k3dViewport: Any = ...
    kAmbientLight: Any = ...
    kAmbientOcclusion: Any = ...
    kAntiAliasing: Any = ...
    kBackfaceCulling: Any = ...
    kBoundingBox: Any = ...
    kCustomLights: Any = ...
    kDefaultMaterial: Any = ...
    kDepthOfField: Any = ...
    kDepthPeeling: Any = ...
    kExcludeAll: Any = ...
    kExcludeCVs: Any = ...
    kExcludeCameras: Any = ...
    kExcludeClipGhosts: Any = ...
    kExcludeControllers: Any = ...
    kExcludeDeformers: Any = ...
    kExcludeDimensions: Any = ...
    kExcludeDynamicConstraints: Any = ...
    kExcludeDynamics: Any = ...
    kExcludeFluids: Any = ...
    kExcludeFollicles: Any = ...
    kExcludeGreasePencils: Any = ...
    kExcludeGrid: Any = ...
    kExcludeHUD: Any = ...
    kExcludeHairSystems: Any = ...
    kExcludeHoldOuts: Any = ...
    kExcludeHulls: Any = ...
    kExcludeIkHandles: Any = ...
    kExcludeImagePlane: Any = ...
    kExcludeJoints: Any = ...
    kExcludeLights: Any = ...
    kExcludeLocators: Any = ...
    kExcludeManipulators: Any = ...
    kExcludeMeshes: Any = ...
    kExcludeMotionTrails: Any = ...
    kExcludeNCloths: Any = ...
    kExcludeNParticles: Any = ...
    kExcludeNRigids: Any = ...
    kExcludeNone: Any = ...
    kExcludeNurbsCurves: Any = ...
    kExcludeNurbsSurfaces: Any = ...
    kExcludeParticleInstancers: Any = ...
    kExcludePivots: Any = ...
    kExcludePlanes: Any = ...
    kExcludePluginShapes: Any = ...
    kExcludeSelectHandles: Any = ...
    kExcludeStrokes: Any = ...
    kExcludeSubdivSurfaces: Any = ...
    kExcludeTextures: Any = ...
    kFlatShaded: Any = ...
    kFogExp: Any = ...
    kFogExp2: Any = ...
    kFogLinear: Any = ...
    kGammaCorrection: Any = ...
    kGouraudShaded: Any = ...
    kImage: Any = ...
    kLightDefault: Any = ...
    kMotionBlur: Any = ...
    kNoLighting: Any = ...
    kObjectSorting: Any = ...
    kProjectionInverseMtx: Any = ...
    kProjectionMtx: Any = ...
    kProjectionTranposeMtx: Any = ...
    kProjectionTranspInverseMtx: Any = ...
    kSceneLights: Any = ...
    kSelectedLights: Any = ...
    kShadeActiveOnly: Any = ...
    kSmoothWireframe: Any = ...
    kTextured: Any = ...
    kTwoSidedLighting: Any = ...
    kUnsorted: Any = ...
    kViewColorTransformEnabled: Any = ...
    kViewDirection: Any = ...
    kViewFarClipValue: Any = ...
    kViewInverseMtx: Any = ...
    kViewMtx: Any = ...
    kViewNearClipValue: Any = ...
    kViewPosition: Any = ...
    kViewProjInverseMtx: Any = ...
    kViewProjMtx: Any = ...
    kViewProjTranposeMtx: Any = ...
    kViewProjTranspInverseMtx: Any = ...
    kViewRight: Any = ...
    kViewTranspInverseMtx: Any = ...
    kViewTransposeMtx: Any = ...
    kViewUnnormalizedFarClipValue: Any = ...
    kViewUnnormlizedNearClipValue: Any = ...
    kViewUp: Any = ...
    kViewportPixelSize: Any = ...
    kWeightedAverage: Any = ...
    kWireFrame: Any = ...
    kWireFrameOnShadedNone: Any = ...
    kWireFrameOnShadedReduced: Any = ...
    kWireframeOnShadedFull: Any = ...
    kWorldInverseMtx: Any = ...
    kWorldMtx: Any = ...
    kWorldTranspInverseMtx: Any = ...
    kWorldTransposeMtx: Any = ...
    kWorldViewInverseMtx: Any = ...
    kWorldViewMtx: Any = ...
    kWorldViewProjInverseMtx: Any = ...
    kWorldViewProjMtx: Any = ...
    kWorldViewProjTranspInverseMtx: Any = ...
    kWorldViewProjTransposeMtx: Any = ...
    kWorldViewTranspInverseMtx: Any = ...
    kWorldViewTransposeMtx: Any = ...
    kXray: Any = ...
    kXrayActiveComponents: Any = ...
    kXrayJoint: Any = ...
    def objectTypeExclusions(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderingDestination(self, *args: Any, **kwargs: Any) -> Any: ...
    def semanticToMatrixType(self, *args: Any, **kwargs: Any) -> Any: ...
    def semanticToTupleType(self, *args: Any, **kwargs: Any) -> Any: ...
    def shadeTemplates(self, *args: Any, **kwargs: Any) -> Any: ...
    def userChangingViewContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def wireOnShadedMode(self, *args: Any, **kwargs: Any) -> Any: ...

class MGeometry:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addIndexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def addVertexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def createIndexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def createVertexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dataTypeString(self, *args: Any, **kwargs: Any) -> Any: ...
    def deleteIndexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def deleteVertexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawModeString(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexBufferCount(self, *args: Any, **kwargs: Any) -> Any: ...
    kAdjacentLineStrip: Any = ...
    kAdjacentLines: Any = ...
    kAdjacentTriangleStrip: Any = ...
    kAdjacentTriangles: Any = ...
    kAll: Any = ...
    kBitangent: Any = ...
    kBoundingBox: Any = ...
    kChar: Any = ...
    kColor: Any = ...
    kDouble: Any = ...
    kFloat: Any = ...
    kInt16: Any = ...
    kInt32: Any = ...
    kInvalidPrimitive: Any = ...
    kInvalidSemantic: Any = ...
    kInvalidType: Any = ...
    kLineStrip: Any = ...
    kLines: Any = ...
    kNormal: Any = ...
    kPatch: Any = ...
    kPoints: Any = ...
    kPosition: Any = ...
    kSelectionHighlighting: Any = ...
    kSelectionOnly: Any = ...
    kShaded: Any = ...
    kTangent: Any = ...
    kTangentWithSign: Any = ...
    kTexture: Any = ...
    kTextured: Any = ...
    kTriangleStrip: Any = ...
    kTriangles: Any = ...
    kUnsignedChar: Any = ...
    kUnsignedInt16: Any = ...
    kUnsignedInt32: Any = ...
    kWireframe: Any = ...
    def primitiveString(self, *args: Any, **kwargs: Any) -> Any: ...
    def semanticString(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertexBufferCount(self, *args: Any, **kwargs: Any) -> Any: ...

class MGeometryExtractor:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    kPolyGeom_BaseMesh: Any = ...
    kPolyGeom_Normal: Any = ...
    kPolyGeom_NotSharing: Any = ...
    def minimumBufferSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def populateIndexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def populateVertexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def primitiveCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertexCount(self, *args: Any, **kwargs: Any) -> Any: ...

class MGeometryIndexMapping:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def component(self, *args: Any, **kwargs: Any) -> Any: ...
    def dagPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def geometryCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexLength(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexStart(self, *args: Any, **kwargs: Any) -> Any: ...

class MGeometryRequirements:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addIndexingRequirement(self, *args: Any, **kwargs: Any) -> Any: ...
    def addVertexRequirement(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexingRequirements(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertexRequirements(self, *args: Any, **kwargs: Any) -> Any: ...

class MGeometryUtilities:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireReferenceGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def displayStatus(self, *args: Any, **kwargs: Any) -> Any: ...
    kActive: Any = ...
    kActiveAffected: Any = ...
    kActiveComponent: Any = ...
    kActiveTemplate: Any = ...
    kDefaultCube: Any = ...
    kDefaultPlane: Any = ...
    kDefaultSphere: Any = ...
    kDormant: Any = ...
    kHilite: Any = ...
    kIntermediateObject: Any = ...
    kInvisible: Any = ...
    kLead: Any = ...
    kLive: Any = ...
    kNoStatus: Any = ...
    kTemplate: Any = ...
    def releaseReferenceGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def wireframeColor(self, *args: Any, **kwargs: Any) -> Any: ...

class MHUDRender:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    kClear: Any = ...
    kHUDRender: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kSceneRender: Any = ...
    kUserDefined: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MIndexBuffer:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquire(self, *args: Any, **kwargs: Any) -> Any: ...
    def commit(self, *args: Any, **kwargs: Any) -> Any: ...
    def dataType(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasCustomResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def lockResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def map(self, *args: Any, **kwargs: Any) -> Any: ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def size(self, *args: Any, **kwargs: Any) -> Any: ...
    def unload(self, *args: Any, **kwargs: Any) -> Any: ...
    def unlockResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def unmap(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...

class MIndexBufferDescriptor:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    component: Any = ...
    dataType: Any = ...
    indexType: Any = ...
    kControlVertex: Any = ...
    kCustom: Any = ...
    kEdgeLine: Any = ...
    kEditPoint: Any = ...
    kFaceCenter: Any = ...
    kHullEdgeCenter: Any = ...
    kHullEdgeLine: Any = ...
    kHullFaceCenter: Any = ...
    kHullTriangle: Any = ...
    kHullUV: Any = ...
    kSubDivEdge: Any = ...
    kTangent: Any = ...
    kTriangle: Any = ...
    kTriangleEdge: Any = ...
    kVertexPoint: Any = ...
    name: Any = ...
    primitive: Any = ...
    primitiveStride: Any = ...

class MIndexBufferDescriptorList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class MInitContext:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    dagPath: Any = ...
    shader: Any = ...

class MInitFeedback:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    customData: Any = ...

class MIntersection:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    barycentricCoordinates: Any = ...
    edgeInterpolantValue: Any = ...
    index: Any = ...
    instanceID: Any = ...
    intersectionPoint: Any = ...
    selectionLevel: Any = ...

class MLightParameterInformation:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def arrayParameterCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def getParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def getParameterTextureHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    kBoolean: Any = ...
    kColor: Any = ...
    kCosConeAngle: Any = ...
    kDecayRate: Any = ...
    kDepthRange: Any = ...
    kDropoff: Any = ...
    kEmitsDiffuse: Any = ...
    kEmitsSpecular: Any = ...
    kFloat: Any = ...
    kFloat2: Any = ...
    kFloat3: Any = ...
    kFloat4: Any = ...
    kFloat4x4Col: Any = ...
    kFloat4x4Row: Any = ...
    kGlobalShadowOn: Any = ...
    kInteger: Any = ...
    kIntensity: Any = ...
    kInvalid: Any = ...
    kIrradianceIn: Any = ...
    kLightEnabled: Any = ...
    kNoSemantic: Any = ...
    kSampler: Any = ...
    kShadowBias: Any = ...
    kShadowColor: Any = ...
    kShadowDirty: Any = ...
    kShadowMap: Any = ...
    kShadowMapSize: Any = ...
    kShadowOn: Any = ...
    kShadowSamp: Any = ...
    kShadowViewProj: Any = ...
    kStartShadowParameters: Any = ...
    kTexture2: Any = ...
    kTextureCube: Any = ...
    kWorldDirection: Any = ...
    kWorldPosition: Any = ...
    def lightPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def lightType(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterList(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterNames(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterSemantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterType(self, *args: Any, **kwargs: Any) -> Any: ...

class MPassContext:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasShaderOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    kBeginRenderSemantic: Any = ...
    kBeginSceneRenderSemantic: Any = ...
    kColorPassSemantic: Any = ...
    kCullBackSemantic: Any = ...
    kCullFrontSemantic: Any = ...
    kDOFPassSemantic: Any = ...
    kDepthPassSemantic: Any = ...
    kEndRenderSemantic: Any = ...
    kEndSceneRenderSemantic: Any = ...
    kMaterialOverrideSemantic: Any = ...
    kMotionVectorPassSemantic: Any = ...
    kNonPEPatternPassSemantic: Any = ...
    kNormalDepthPassSemantic: Any = ...
    kOpaqueGeometrySemantic: Any = ...
    kOpaqueUISemantic: Any = ...
    kPEPatternPassSemantic: Any = ...
    kPostUIGeometrySemantic: Any = ...
    kPreUIGeometrySemantic: Any = ...
    kSelectionPassSemantic: Any = ...
    kShadowPassSemantic: Any = ...
    kTransparentGeometrySemantic: Any = ...
    kTransparentPeelAndAvgSemantic: Any = ...
    kTransparentPeelSemantic: Any = ...
    kTransparentUISemantic: Any = ...
    kTransparentWeightedAvgSemantic: Any = ...
    kUIGeometrySemantic: Any = ...
    kUserPassSemantic: Any = ...
    kXrayUISemantic: Any = ...
    def passIdentifier(self, *args: Any, **kwargs: Any) -> Any: ...
    def passSemantics(self, *args: Any, **kwargs: Any) -> Any: ...
    def shaderOverrideInstance(self, *args: Any, **kwargs: Any) -> Any: ...

class MPresentTarget:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    kCenterBuffer: Any = ...
    kClear: Any = ...
    kHUDRender: Any = ...
    kLeftBuffer: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kRightBuffer: Any = ...
    kSceneRender: Any = ...
    kUserDefined: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def presentDepth(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPresentDepth(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTargetBackBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetBackBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxComponentConverter:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addIntersection(self, *args: Any, **kwargs: Any) -> Any: ...
    def component(self, *args: Any, **kwargs: Any) -> Any: ...
    def initialize(self, *args: Any, **kwargs: Any) -> Any: ...
    def selectionMask(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxDrawOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def boundingBox(self, *args: Any, **kwargs: Any) -> Any: ...
    def disableInternalBoundingBoxDraw(self, *args: Any, **kwargs: Any) -> Any: ...
    def excludedFromPostEffects(self, *args: Any, **kwargs: Any) -> Any: ...
    def handleTraceMessage(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def isBounded(self, *args: Any, **kwargs: Any) -> Any: ...
    def isTransparent(self, *args: Any, **kwargs: Any) -> Any: ...
    def pointSnappingActive(self, *args: Any, **kwargs: Any) -> Any: ...
    def prepareForDraw(self, *args: Any, **kwargs: Any) -> Any: ...
    def refineSelectionPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def traceCallSequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def transform(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateSelectionGranularity(self, *args: Any, **kwargs: Any) -> Any: ...
    def userSelect(self, *args: Any, **kwargs: Any) -> Any: ...
    def wantUserSelection(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxGeometryOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def cleanUp(self, *args: Any, **kwargs: Any) -> Any: ...
    def configCache(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFrameContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def handleTraceMessage(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def isIndexingDirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def isStreamDirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def pointSnappingActive(self, *args: Any, **kwargs: Any) -> Any: ...
    def populateGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def refineSelectionPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def requiresGeometryUpdate(self, *args: Any, **kwargs: Any) -> Any: ...
    def requiresUpdateRenderItems(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportsEvaluationManagerParallelUpdate(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportsVP2CustomCaching(self, *args: Any, **kwargs: Any) -> Any: ...
    def traceCallSequence(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateDG(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateRenderItems(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateSelectionGranularity(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxImagePlaneOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxIndexBufferMutator:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def mutateIndexing(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxPrimitiveGenerator:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def computeIndexCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def generateIndexing(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxShaderOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def activateKey(self, *args: Any, **kwargs: Any) -> Any: ...
    def addGeometryRequirement(self, *args: Any, **kwargs: Any) -> Any: ...
    def addGeometryRequirements(self, *args: Any, **kwargs: Any) -> Any: ...
    def addIndexingRequirement(self, *args: Any, **kwargs: Any) -> Any: ...
    def addShaderSignature(self, *args: Any, **kwargs: Any) -> Any: ...
    def boundingBoxExtraScale(self, *args: Any, **kwargs: Any) -> Any: ...
    def draw(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def endUpdate(self, *args: Any, **kwargs: Any) -> Any: ...
    def handlesConsolidatedGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def handlesDraw(self, *args: Any, **kwargs: Any) -> Any: ...
    def initialize(self, *args: Any, **kwargs: Any) -> Any: ...
    def initialize2(self, *args: Any, **kwargs: Any) -> Any: ...
    def isTransparent(self, *args: Any, **kwargs: Any) -> Any: ...
    def nonTexturedShaderInstance(self, *args: Any, **kwargs: Any) -> Any: ...
    def overridesDrawState(self, *args: Any, **kwargs: Any) -> Any: ...
    def overridesNonMaterialItems(self, *args: Any, **kwargs: Any) -> Any: ...
    def rebuildAlways(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGeometryRequirements(self, *args: Any, **kwargs: Any) -> Any: ...
    def shaderInstance(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportsAdvancedTransparency(self, *args: Any, **kwargs: Any) -> Any: ...
    def terminateKey(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateDG(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateDevice(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxShadingNodeOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def allowConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def fragmentName(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCustomMappings(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputForConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateDG(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def valueChangeRequiresFragmentRebuild(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxSubSceneOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addInstanceTransform(self, *args: Any, **kwargs: Any) -> Any: ...
    def addUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def areUIDrawablesDirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def furtherUpdateRequired(self, *args: Any, **kwargs: Any) -> Any: ...
    def getInstancedSelectionPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def getSelectionPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def pointSnappingActive(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAllInstances(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeExtraInstanceData(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeInstance(self, *args: Any, **kwargs: Any) -> Any: ...
    def requiresUpdate(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAllowTransparentInstances(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExtraInstanceData(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGeometryForRenderItem(self, *args: Any, **kwargs: Any) -> Any: ...
    def setInstanceTransformArray(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateInstanceTransform(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateSelectionGranularity(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxSurfaceShadingNodeOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def allowConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def bumpAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def fragmentName(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCustomMappings(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputForConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def primaryColorParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def transparencyParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateDG(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def valueChangeRequiresFragmentRebuild(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxVertexBufferGenerator:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def createVertexStream(self, *args: Any, **kwargs: Any) -> Any: ...
    def getSourceIndexing(self, *args: Any, **kwargs: Any) -> Any: ...
    def getSourceStreams(self, *args: Any, **kwargs: Any) -> Any: ...

class MPxVertexBufferMutator:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def modifyVertexStream(self, *args: Any, **kwargs: Any) -> Any: ...

class MQuadRender:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def blendStateOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearOperation(self, *args: Any, **kwargs: Any) -> Any: ...
    def depthStencilStateOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    kClear: Any = ...
    kHUDRender: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kSceneRender: Any = ...
    kUserDefined: Any = ...
    mClearOperation: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def rasterizerStateOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def shader(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MRasterizerState:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def desc(self, *args: Any, **kwargs: Any) -> Any: ...
    kCullBack: Any = ...
    kCullFront: Any = ...
    kCullNone: Any = ...
    kFillSolid: Any = ...
    kFillWireFrame: Any = ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...

class MRasterizerStateDesc:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    antialiasedLineEnable: Any = ...
    cullMode: Any = ...
    depthBias: Any = ...
    depthBiasClamp: Any = ...
    depthBiasIsFloat: Any = ...
    depthClipEnable: Any = ...
    fillMode: Any = ...
    frontCounterClockwise: Any = ...
    multiSampleEnable: Any = ...
    scissorEnable: Any = ...
    def setDefaults(self, *args: Any, **kwargs: Any) -> Any: ...
    slopeScaledDepthBias: Any = ...

class MRenderItem:
    DecorationItem: Any = ...
    DrawOnlyWhenDefaultMaterialActive: Any = ...
    IgnoreDefaultMaterialMode: Any = ...
    InternalItem: Any = ...
    InternalMaterialItem: Any = ...
    InternalTexturedMaterialItem: Any = ...
    InternalUnsupportedMaterialItem: Any = ...
    MaterialSceneItem: Any = ...
    NonMaterialSceneItem: Any = ...
    OverrideNonMaterialItem: Any = ...
    SkipWhenDefaultMaterialActive: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def allowIsolateSelectCopy(self, *args: Any, **kwargs: Any) -> Any: ...
    def associateWithIndexBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def availableShaderParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def boundingBox(self, *args: Any, **kwargs: Any) -> Any: ...
    def castsShadows(self, *args: Any, **kwargs: Any) -> Any: ...
    def component(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def customData(self, *args: Any, **kwargs: Any) -> Any: ...
    def depthPriority(self, *args: Any, **kwargs: Any) -> Any: ...
    def destroy(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def enable(self, *args: Any, **kwargs: Any) -> Any: ...
    def excludedFromPostEffects(self, *args: Any, **kwargs: Any) -> Any: ...
    def geometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getCustomData(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDefaultMaterialHandling(self, *args: Any, **kwargs: Any) -> Any: ...
    def getShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def getShaderParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def isCompatibleWithMayaInstancer(self, *args: Any, **kwargs: Any) -> Any: ...
    def isConsolidated(self, *args: Any, **kwargs: Any) -> Any: ...
    def isEnabled(self, *args: Any, **kwargs: Any) -> Any: ...
    def isIsolateSelectCopy(self, *args: Any, **kwargs: Any) -> Any: ...
    def isShaderFromNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def objectTypeExclusionFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def primitive(self, *args: Any, **kwargs: Any) -> Any: ...
    def primitiveAndStride(self, *args: Any, **kwargs: Any) -> Any: ...
    def receivesShadows(self, *args: Any, **kwargs: Any) -> Any: ...
    def requiredVertexBuffers(self, *args: Any, **kwargs: Any) -> Any: ...
    sActiveLineDepthPriority: Any = ...
    sActivePointDepthPriority: Any = ...
    sActiveWireDepthPriority: Any = ...
    sDormantFilledDepthPriority: Any = ...
    sDormantPointDepthPriority: Any = ...
    sDormantWireDepthPriority: Any = ...
    sHiliteWireDepthPriority: Any = ...
    sSelectionDepthPriority: Any = ...
    def selectionMask(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAllowIsolateSelectCopy(self, *args: Any, **kwargs: Any) -> Any: ...
    def setBoundingBox(self, *args: Any, **kwargs: Any) -> Any: ...
    def setCastsShadows(self, *args: Any, **kwargs: Any) -> Any: ...
    def setCompatibleWithMayaInstancer(self, *args: Any, **kwargs: Any) -> Any: ...
    def setCustomData(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDefaultMaterialHandling(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDepthPriority(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDrawMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExcludedFromPostEffects(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMatrix(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObjectTypeExclusionFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPrimitive(self, *args: Any, **kwargs: Any) -> Any: ...
    def setReceivesShadows(self, *args: Any, **kwargs: Any) -> Any: ...
    def setSelectionMask(self, *args: Any, **kwargs: Any) -> Any: ...
    def setShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def setShaderFromNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTreatAsTransparent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWantConsolidation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWantSubSceneConsolidation(self, *args: Any, **kwargs: Any) -> Any: ...
    def shadingComponent(self, *args: Any, **kwargs: Any) -> Any: ...
    def sourceDagPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def sourceIndexMapping(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    def wantConsolidation(self, *args: Any, **kwargs: Any) -> Any: ...
    def wantSubSceneConsolidation(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderItemList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexOf(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderOperation:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    kClear: Any = ...
    kHUDRender: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kSceneRender: Any = ...
    kUserDefined: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderOverride:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def cleanup(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFrameContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def nextRenderOperation(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderOperation(self, *args: Any, **kwargs: Any) -> Any: ...
    def select(self, *args: Any, **kwargs: Any) -> Any: ...
    def setup(self, *args: Any, **kwargs: Any) -> Any: ...
    def startOperationIterator(self, *args: Any, **kwargs: Any) -> Any: ...
    def supportedDrawAPIs(self, *args: Any, **kwargs: Any) -> Any: ...
    def uiName(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderParameters:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def getParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def isArrayParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterList(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterType(self, *args: Any, **kwargs: Any) -> Any: ...
    def semantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def setArrayParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def setParameter(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderProfile:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addRenderer(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasRenderer(self, *args: Any, **kwargs: Any) -> Any: ...
    kMayaD3D: Any = ...
    kMayaOpenGL: Any = ...
    kMayaSoftware: Any = ...
    def numberOfRenderers(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderTarget:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def freeRawData(self, *args: Any, **kwargs: Any) -> Any: ...
    def rawData(self, *args: Any, **kwargs: Any) -> Any: ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetDescription(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateDescription(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderTargetAssignment:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    target: Any = ...

class MRenderTargetDescription:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def allowsUnorderedAccess(self, *args: Any, **kwargs: Any) -> Any: ...
    def arraySliceCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def compatibleWithDescription(self, *args: Any, **kwargs: Any) -> Any: ...
    def height(self, *args: Any, **kwargs: Any) -> Any: ...
    def isCubeMap(self, *args: Any, **kwargs: Any) -> Any: ...
    def multiSampleCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def rasterFormat(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAllowsUnorderedAccess(self, *args: Any, **kwargs: Any) -> Any: ...
    def setArraySliceCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def setHeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIsCubeMap(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMultiSampleCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRasterFormat(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWidth(self, *args: Any, **kwargs: Any) -> Any: ...
    def width(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderTargetManager:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireRenderTargetFromScreen(self, *args: Any, **kwargs: Any) -> Any: ...
    def formatSupportsSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def releaseRenderTarget(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderUtilities:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireSwatchDrawContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireUVTextureDrawContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def blitTargetToGL(self, *args: Any, **kwargs: Any) -> Any: ...
    def blitTargetToImage(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawSimpleMesh(self, *args: Any, **kwargs: Any) -> Any: ...
    kAmbientLight: Any = ...
    kDefaultLights: Any = ...
    kOrthogonalCameraCloseUp: Any = ...
    kOrthogonalCameraWithMargin: Any = ...
    kPerspectiveCamera: Any = ...
    kSwatchLight: Any = ...
    def releaseDrawContext(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderMaterialViewerGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def swatchBackgroundColor(self, *args: Any, **kwargs: Any) -> Any: ...

class MRenderer:
    def GPUDeviceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def GPUmaximumPrimitiveCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def GPUmaximumVertexBufferSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def activeRenderOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def copyTargetToScreen(self, *args: Any, **kwargs: Any) -> Any: ...
    def deregisterOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def disableChangeManagementUntilNextRefresh(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawAPI(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawAPIIsOpenGL(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawAPIVersion(self, *args: Any, **kwargs: Any) -> Any: ...
    def findRenderOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFragmentManager(self, *args: Any, **kwargs: Any) -> Any: ...
    def getRenderTargetManager(self, *args: Any, **kwargs: Any) -> Any: ...
    def getShaderManager(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTextureManager(self, *args: Any, **kwargs: Any) -> Any: ...
    kA8: Any = ...
    kA8B8G8R8: Any = ...
    kAllDevices: Any = ...
    kB5G5R5A1: Any = ...
    kB5G6R5: Any = ...
    kB8G8R8A8: Any = ...
    kB8G8R8X8: Any = ...
    kBC6H_SF16: Any = ...
    kBC6H_UF16: Any = ...
    kBC7_UNORM: Any = ...
    kBC7_UNORM_SRGB: Any = ...
    kD24S8: Any = ...
    kD24X8: Any = ...
    kD32_FLOAT: Any = ...
    kDXT1_UNORM: Any = ...
    kDXT1_UNORM_SRGB: Any = ...
    kDXT2_UNORM: Any = ...
    kDXT2_UNORM_PREALPHA: Any = ...
    kDXT2_UNORM_SRGB: Any = ...
    kDXT3_UNORM: Any = ...
    kDXT3_UNORM_PREALPHA: Any = ...
    kDXT3_UNORM_SRGB: Any = ...
    kDXT4_SNORM: Any = ...
    kDXT4_UNORM: Any = ...
    kDXT5_SNORM: Any = ...
    kDXT5_UNORM: Any = ...
    kDirectX11: Any = ...
    kL16: Any = ...
    kL8: Any = ...
    kNone: Any = ...
    kNumberOfRasterFormats: Any = ...
    kOpenGL: Any = ...
    kOpenGLCoreProfile: Any = ...
    kR10G10B10A2_UINT: Any = ...
    kR10G10B10A2_UNORM: Any = ...
    kR16G16B16A16_FLOAT: Any = ...
    kR16G16B16A16_SINT: Any = ...
    kR16G16B16A16_SNORM: Any = ...
    kR16G16B16A16_UINT: Any = ...
    kR16G16B16A16_UNORM: Any = ...
    kR16G16_FLOAT: Any = ...
    kR16G16_SINT: Any = ...
    kR16G16_SNORM: Any = ...
    kR16G16_UINT: Any = ...
    kR16G16_UNORM: Any = ...
    kR16_FLOAT: Any = ...
    kR16_SINT: Any = ...
    kR16_SNORM: Any = ...
    kR16_UINT: Any = ...
    kR16_UNORM: Any = ...
    kR1_UNORM: Any = ...
    kR24G8: Any = ...
    kR24X8: Any = ...
    kR32G32B32A32_FLOAT: Any = ...
    kR32G32B32A32_SINT: Any = ...
    kR32G32B32A32_UINT: Any = ...
    kR32G32B32_FLOAT: Any = ...
    kR32G32B32_SINT: Any = ...
    kR32G32B32_UINT: Any = ...
    kR32G32_FLOAT: Any = ...
    kR32G32_SINT: Any = ...
    kR32G32_UINT: Any = ...
    kR32_FLOAT: Any = ...
    kR32_SINT: Any = ...
    kR32_UINT: Any = ...
    kR8G8B8A8_SINT: Any = ...
    kR8G8B8A8_SNORM: Any = ...
    kR8G8B8A8_UINT: Any = ...
    kR8G8B8A8_UNORM: Any = ...
    kR8G8B8X8: Any = ...
    kR8G8_SINT: Any = ...
    kR8G8_SNORM: Any = ...
    kR8G8_UINT: Any = ...
    kR8G8_UNORM: Any = ...
    kR8_SINT: Any = ...
    kR8_SNORM: Any = ...
    kR8_UINT: Any = ...
    kR8_UNORM: Any = ...
    kR9G9B9E5_FLOAT: Any = ...
    def needEvaluateAllLights(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputTargetSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def registerOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def render(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderOverrideCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderOverrideName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGeometryDrawDirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLightRequiresShadows(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLightsAndShadowsDirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRenderOverrideName(self, *args: Any, **kwargs: Any) -> Any: ...

class MSamplerState:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def desc(self, *args: Any, **kwargs: Any) -> Any: ...
    kAnisotropic: Any = ...
    kMinLinear_MagMipPoint: Any = ...
    kMinLinear_MagPoint_MipLinear: Any = ...
    kMinMagLinear_MipPoint: Any = ...
    kMinMagMipLinear: Any = ...
    kMinMagMipPoint: Any = ...
    kMinMagPoint_MipLinear: Any = ...
    kMinPoint_MagLinear_MipPoint: Any = ...
    kMinPoint_MagMipLinear: Any = ...
    kTexBorder: Any = ...
    kTexClamp: Any = ...
    kTexMirror: Any = ...
    kTexWrap: Any = ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...

class MSamplerStateDesc:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    addressU: Any = ...
    addressV: Any = ...
    addressW: Any = ...
    borderColor: Any = ...
    comparisonFn: Any = ...
    coordCount: Any = ...
    elementIndex: Any = ...
    filter: Any = ...
    maxAnisotropy: Any = ...
    maxLOD: Any = ...
    minLOD: Any = ...
    mipLODBias: Any = ...
    def setDefaults(self, *args: Any, **kwargs: Any) -> Any: ...

class MSceneRender:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addPostUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def addPreUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def cameraOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearOperation(self, *args: Any, **kwargs: Any) -> Any: ...
    def cullingOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def displayModeOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def fragmentName(self, *args: Any, **kwargs: Any) -> Any: ...
    def getObjectTypeExclusions(self, *args: Any, **kwargs: Any) -> Any: ...
    def getParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    kAmbientLight: Any = ...
    kBoundingBox: Any = ...
    kClear: Any = ...
    kCullBackFaces: Any = ...
    kCullFrontFaces: Any = ...
    kCullNone: Any = ...
    kDefaultMaterial: Any = ...
    kExcludeAll: Any = ...
    kExcludeCVs: Any = ...
    kExcludeCameras: Any = ...
    kExcludeDeformers: Any = ...
    kExcludeDimensions: Any = ...
    kExcludeDynamicConstraints: Any = ...
    kExcludeDynamics: Any = ...
    kExcludeFluids: Any = ...
    kExcludeFollicles: Any = ...
    kExcludeGrid: Any = ...
    kExcludeHairSystems: Any = ...
    kExcludeHoldOuts: Any = ...
    kExcludeHulls: Any = ...
    kExcludeIkHandles: Any = ...
    kExcludeImagePlane: Any = ...
    kExcludeJoints: Any = ...
    kExcludeLights: Any = ...
    kExcludeLocators: Any = ...
    kExcludeManipulators: Any = ...
    kExcludeMeshes: Any = ...
    kExcludeMotionTrails: Any = ...
    kExcludeNCloths: Any = ...
    kExcludeNParticles: Any = ...
    kExcludeNRigids: Any = ...
    kExcludeNone: Any = ...
    kExcludeNurbsCurves: Any = ...
    kExcludeNurbsSurfaces: Any = ...
    kExcludeParticleInstancers: Any = ...
    kExcludePivots: Any = ...
    kExcludePlanes: Any = ...
    kExcludeSelectHandles: Any = ...
    kExcludeStrokes: Any = ...
    kExcludeSubdivSurfaces: Any = ...
    kExcludeTextures: Any = ...
    kFlatShaded: Any = ...
    kHUDRender: Any = ...
    kLightDefault: Any = ...
    kNoCullingOverride: Any = ...
    kNoDisplayModeOverride: Any = ...
    kNoLight: Any = ...
    kNoLightingModeOverride: Any = ...
    kNoSceneFilterOverride: Any = ...
    kPostEffectDisableAll: Any = ...
    kPostEffectDisableDOF: Any = ...
    kPostEffectDisableMotionBlur: Any = ...
    kPostEffectDisableNone: Any = ...
    kPostEffectDisableSSAO: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kRenderAllItems: Any = ...
    kRenderNonShadedItems: Any = ...
    kRenderOpaqueShadedItems: Any = ...
    kRenderPostSceneUIItems: Any = ...
    kRenderPreSceneUIItems: Any = ...
    kRenderShadedItems: Any = ...
    kRenderTransparentShadedItems: Any = ...
    kRenderUIItems: Any = ...
    kSceneLights: Any = ...
    kSceneRender: Any = ...
    kSelectedLights: Any = ...
    kShadeActiveOnly: Any = ...
    kShaded: Any = ...
    kTextured: Any = ...
    kUserDefined: Any = ...
    kWireFrame: Any = ...
    def lightModeOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    mClearOperation: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def objectSetOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def objectTypeExclusions(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def postEffectsOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def postRender(self, *args: Any, **kwargs: Any) -> Any: ...
    def postSceneRender(self, *args: Any, **kwargs: Any) -> Any: ...
    def preRender(self, *args: Any, **kwargs: Any) -> Any: ...
    def preSceneRender(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderFilterOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def shaderOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def shadowEnableOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MSelectionContext:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    kComponent: Any = ...
    kEdge: Any = ...
    kFace: Any = ...
    kNone: Any = ...
    kObject: Any = ...
    kVertex: Any = ...
    selectionLevel: Any = ...

class MSelectionInfo:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    alignmentMatrix: Any = ...
    cursorPoint: Any = ...
    isRay: Any = ...
    isSingleSelection: Any = ...
    localRay: Any = ...
    pointSnapping: Any = ...
    selectClosest: Any = ...
    def selectForHilite(self, *args: Any, **kwargs: Any) -> Any: ...
    selectOnHilitedOnly: Any = ...
    selectRect: Any = ...
    def selectable(self, *args: Any, **kwargs: Any) -> Any: ...
    def selectableComponent(self, *args: Any, **kwargs: Any) -> Any: ...

class MShaderCompileMacro:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    definition: Any = ...
    name: Any = ...

class MShaderInstance:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def activatePass(self, *args: Any, **kwargs: Any) -> Any: ...
    def addInputFragment(self, *args: Any, **kwargs: Any) -> Any: ...
    def addInputFragmentForMultiParams(self, *args: Any, **kwargs: Any) -> Any: ...
    def addOutputFragment(self, *args: Any, **kwargs: Any) -> Any: ...
    def annotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind(self, *args: Any, **kwargs: Any) -> Any: ...
    def clone(self, *args: Any, **kwargs: Any) -> Any: ...
    def createShaderInstanceWithColorManagementFragment(self, *args: Any, **kwargs: Any) -> Any: ...
    def getArraySize(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPassCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def isArrayParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def isTransparent(self, *args: Any, **kwargs: Any) -> Any: ...
    def isVaryingParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    kAnisotropyShader: Any = ...
    kAnisotropyShader2: Any = ...
    kBoolean: Any = ...
    kDisplacementPosShader: Any = ...
    kFloat: Any = ...
    kFloat2: Any = ...
    kFloat3: Any = ...
    kFloat4: Any = ...
    kFloat4x4Col: Any = ...
    kFloat4x4Row: Any = ...
    kGeometryShader: Any = ...
    kGlossShader: Any = ...
    kGlossShader2: Any = ...
    kInteger: Any = ...
    kInvalid: Any = ...
    kNormalShader: Any = ...
    kNormalShader2: Any = ...
    kPixelShader: Any = ...
    kReflectanceShader: Any = ...
    kReflectanceShader2: Any = ...
    kRotationAngleShader: Any = ...
    kRotationAngleShader2: Any = ...
    kRoughnessShader: Any = ...
    kRoughnessShader2: Any = ...
    kSampler: Any = ...
    kTexture1: Any = ...
    kTexture2: Any = ...
    kTexture3: Any = ...
    kTextureCube: Any = ...
    kVertexShader: Any = ...
    def parameterDefaultValue(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterList(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterSemantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameterType(self, *args: Any, **kwargs: Any) -> Any: ...
    def passAnnotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def postDrawCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def preDrawCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def renameParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def requiredVertexBuffers(self, *args: Any, **kwargs: Any) -> Any: ...
    def resourceName(self, *args: Any, **kwargs: Any) -> Any: ...
    def semantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def setArrayParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAsVarying(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIsTransparent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setParameter(self, *args: Any, **kwargs: Any) -> Any: ...
    def setSemantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def techniqueAnnotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def techniqueNames(self, *args: Any, **kwargs: Any) -> Any: ...
    def uiName(self, *args: Any, **kwargs: Any) -> Any: ...
    def uiWidget(self, *args: Any, **kwargs: Any) -> Any: ...
    def unbind(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateParameters(self, *args: Any, **kwargs: Any) -> Any: ...
    def writeEffectSourceToFile(self, *args: Any, **kwargs: Any) -> Any: ...

class MShaderManager:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addShaderIncludePath(self, *args: Any, **kwargs: Any) -> Any: ...
    def addShaderPath(self, *args: Any, **kwargs: Any) -> Any: ...
    def clearEffectCache(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEffectsBufferShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEffectsFileShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def getEffectsTechniques(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFragmentShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLastError(self, *args: Any, **kwargs: Any) -> Any: ...
    def getLastErrorSource(self, *args: Any, **kwargs: Any) -> Any: ...
    def getShaderFromNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def getStockShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def isSupportedShaderSemantic(self, *args: Any, **kwargs: Any) -> Any: ...
    k3dBlinnShader: Any = ...
    k3dCPVDashLineShader: Any = ...
    k3dCPVFatPointShader: Any = ...
    k3dCPVShader: Any = ...
    k3dCPVSolidShader: Any = ...
    k3dCPVThickDashLineShader: Any = ...
    k3dCPVThickLineShader: Any = ...
    k3dColorLookupFatPointShader: Any = ...
    k3dColorOpacityLookupFatPointShader: Any = ...
    k3dDashLineShader: Any = ...
    k3dDefaultMaterialShader: Any = ...
    k3dDepthShader: Any = ...
    k3dFatPointShader: Any = ...
    k3dFloat2NumericShader: Any = ...
    k3dFloat3NumericShader: Any = ...
    k3dFloatNumericShader: Any = ...
    k3dIntegerNumericShader: Any = ...
    k3dIsotropicStandardSurfaceShader: Any = ...
    k3dOpacityLookupFatPointShader: Any = ...
    k3dPointLightShadowerShader: Any = ...
    k3dPointVectorShader: Any = ...
    k3dShadowerShader: Any = ...
    k3dSolidShader: Any = ...
    k3dSolidTextureShader: Any = ...
    k3dStandardSurfaceShader: Any = ...
    k3dStippleShader: Any = ...
    k3dThickDashLineShader: Any = ...
    k3dThickLineShader: Any = ...
    def releaseShader(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeEffectFromCache(self, *args: Any, **kwargs: Any) -> Any: ...
    def shaderIncludePaths(self, *args: Any, **kwargs: Any) -> Any: ...
    def shaderPaths(self, *args: Any, **kwargs: Any) -> Any: ...

class MStateManager:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireBlendState(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireDepthStencilState(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireRasterizerState(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireSamplerState(self, *args: Any, **kwargs: Any) -> Any: ...
    def getBlendState(self, *args: Any, **kwargs: Any) -> Any: ...
    def getDepthStencilState(self, *args: Any, **kwargs: Any) -> Any: ...
    def getMaxSamplerCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def getRasterizerState(self, *args: Any, **kwargs: Any) -> Any: ...
    def getSamplerState(self, *args: Any, **kwargs: Any) -> Any: ...
    kCompareAlways: Any = ...
    kCompareEqual: Any = ...
    kCompareGreater: Any = ...
    kCompareGreaterEqual: Any = ...
    kCompareLess: Any = ...
    kCompareLessEqual: Any = ...
    kCompareNever: Any = ...
    kCompareNotEqual: Any = ...
    kDomainShader: Any = ...
    kGeometryShader: Any = ...
    kHullShader: Any = ...
    kNoShader: Any = ...
    kPixelShader: Any = ...
    kVertexShader: Any = ...
    def releaseBlendState(self, *args: Any, **kwargs: Any) -> Any: ...
    def releaseDepthStencilState(self, *args: Any, **kwargs: Any) -> Any: ...
    def releaseRasterizerState(self, *args: Any, **kwargs: Any) -> Any: ...
    def releaseSamplerState(self, *args: Any, **kwargs: Any) -> Any: ...
    def setBlendState(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDepthStencilState(self, *args: Any, **kwargs: Any) -> Any: ...
    def setRasterizerState(self, *args: Any, **kwargs: Any) -> Any: ...
    def setSamplerState(self, *args: Any, **kwargs: Any) -> Any: ...

class MStencilOpDesc:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDefaults(self, *args: Any, **kwargs: Any) -> Any: ...
    stencilDepthFailOp: Any = ...
    stencilFailOp: Any = ...
    stencilFunc: Any = ...
    stencilPassOp: Any = ...

class MSubSceneContainer:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    def getIterator(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class MSubSceneContainerIterator:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def destroy(self, *args: Any, **kwargs: Any) -> Any: ...
    def next(self, *args: Any, **kwargs: Any) -> Any: ...
    def reset(self, *args: Any, **kwargs: Any) -> Any: ...

class MSwatchRenderBase:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancelCurrentSwatchRender(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancelParallelRendering(self, *args: Any, **kwargs: Any) -> Any: ...
    def doIteration(self, *args: Any, **kwargs: Any) -> Any: ...
    def finishParallelRender(self, *args: Any, **kwargs: Any) -> Any: ...
    def image(self, *args: Any, **kwargs: Any) -> Any: ...
    def node(self, *args: Any, **kwargs: Any) -> Any: ...
    def renderParallel(self, *args: Any, **kwargs: Any) -> Any: ...
    renderQuality: Any = ...
    def resolution(self, *args: Any, **kwargs: Any) -> Any: ...
    def swatchNode(self, *args: Any, **kwargs: Any) -> Any: ...

class MTargetBlendDesc:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    alphaBlendOperation: Any = ...
    alphaDestinationBlend: Any = ...
    alphaSourceBlend: Any = ...
    blendEnable: Any = ...
    blendOperation: Any = ...
    destinationBlend: Any = ...
    def setDefaults(self, *args: Any, **kwargs: Any) -> Any: ...
    sourceBlend: Any = ...
    targetWriteMask: Any = ...

class MTexture:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def bytesPerPixel(self, *args: Any, **kwargs: Any) -> Any: ...
    def freeRawData(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAlpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasTransparentAlpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasZeroAlpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def rawData(self, *args: Any, **kwargs: Any) -> Any: ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setHasAlpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def setHasTransparentAlpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def setHasZeroAlpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def textureDescription(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...

class MTextureAssignment:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    texture: Any = ...

class MTextureDescription:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    fArraySlices: Any = ...
    fBytesPerRow: Any = ...
    fBytesPerSlice: Any = ...
    fDepth: Any = ...
    fEnvMapType: Any = ...
    fFormat: Any = ...
    fHeight: Any = ...
    fMipmaps: Any = ...
    fTextureType: Any = ...
    fWidth: Any = ...
    kCubeMap: Any = ...
    kDepthTexture: Any = ...
    kEnvCrossHoriz: Any = ...
    kEnvCrossVert: Any = ...
    kEnvCubemap: Any = ...
    kEnvHemiSphere: Any = ...
    kEnvLatLong: Any = ...
    kEnvNone: Any = ...
    kEnvSphere: Any = ...
    kImage1D: Any = ...
    kImage1DArray: Any = ...
    kImage2D: Any = ...
    kImage2DArray: Any = ...
    kNumberOfEnvMapTypes: Any = ...
    kNumberOfTextureTypes: Any = ...
    kVolumeTexture: Any = ...
    def setToDefault2DTexture(self, *args: Any, **kwargs: Any) -> Any: ...

class MTextureManager:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireDepthTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquireTiledTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def addImagePath(self, *args: Any, **kwargs: Any) -> Any: ...
    def imagePaths(self, *args: Any, **kwargs: Any) -> Any: ...
    def releaseTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def saveTexture(self, *args: Any, **kwargs: Any) -> Any: ...

class MTextureUpdateRegion:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    fXRangeMax: Any = ...
    fXRangeMin: Any = ...
    fYRangeMax: Any = ...
    fYRangeMin: Any = ...
    fZRangeMax: Any = ...
    fZRangeMin: Any = ...

class MUIDrawManager:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def arc(self, *args: Any, **kwargs: Any) -> Any: ...
    def arc2d(self, *args: Any, **kwargs: Any) -> Any: ...
    def beginDrawInXray(self, *args: Any, **kwargs: Any) -> Any: ...
    def beginDrawable(self, *args: Any, **kwargs: Any) -> Any: ...
    def box(self, *args: Any, **kwargs: Any) -> Any: ...
    def capsule(self, *args: Any, **kwargs: Any) -> Any: ...
    def circle(self, *args: Any, **kwargs: Any) -> Any: ...
    def circle2d(self, *args: Any, **kwargs: Any) -> Any: ...
    def cone(self, *args: Any, **kwargs: Any) -> Any: ...
    def cylinder(self, *args: Any, **kwargs: Any) -> Any: ...
    def depthPriority(self, *args: Any, **kwargs: Any) -> Any: ...
    def endDrawInXray(self, *args: Any, **kwargs: Any) -> Any: ...
    def endDrawable(self, *args: Any, **kwargs: Any) -> Any: ...
    def getFontList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getIconNames(self, *args: Any, **kwargs: Any) -> Any: ...
    def icon(self, *args: Any, **kwargs: Any) -> Any: ...
    kAutomatic: Any = ...
    kCenter: Any = ...
    kClosedLine: Any = ...
    kDashed: Any = ...
    kDefaultFontSize: Any = ...
    kDotted: Any = ...
    kFlat: Any = ...
    kInclineItalic: Any = ...
    kInclineNormal: Any = ...
    kInclineOblique: Any = ...
    kLeft: Any = ...
    kLineNone: Any = ...
    kLineOverline: Any = ...
    kLineStrikeoutLine: Any = ...
    kLineStrip: Any = ...
    kLineUnderline: Any = ...
    kLines: Any = ...
    kNonSelectable: Any = ...
    kPoints: Any = ...
    kRight: Any = ...
    kSelectable: Any = ...
    kShaded: Any = ...
    kShortDashed: Any = ...
    kShortDotted: Any = ...
    kSmallFontSize: Any = ...
    kSolid: Any = ...
    kStippled: Any = ...
    kStretchCondensed: Any = ...
    kStretchExpanded: Any = ...
    kStretchExtraCondensed: Any = ...
    kStretchExtraExpanded: Any = ...
    kStretchSemiCondensed: Any = ...
    kStretchSemiExpanded: Any = ...
    kStretchUltraCondensed: Any = ...
    kStretchUltraExpanded: Any = ...
    kStretchUnstretched: Any = ...
    kTriStrip: Any = ...
    kTriangles: Any = ...
    kWeightBlack: Any = ...
    kWeightBold: Any = ...
    kWeightDemiBold: Any = ...
    kWeightLight: Any = ...
    kWeightNormal: Any = ...
    def line(self, *args: Any, **kwargs: Any) -> Any: ...
    def line2d(self, *args: Any, **kwargs: Any) -> Any: ...
    def lineList(self, *args: Any, **kwargs: Any) -> Any: ...
    def lineStrip(self, *args: Any, **kwargs: Any) -> Any: ...
    def mesh(self, *args: Any, **kwargs: Any) -> Any: ...
    def mesh2d(self, *args: Any, **kwargs: Any) -> Any: ...
    def point(self, *args: Any, **kwargs: Any) -> Any: ...
    def point2d(self, *args: Any, **kwargs: Any) -> Any: ...
    def points(self, *args: Any, **kwargs: Any) -> Any: ...
    def rect(self, *args: Any, **kwargs: Any) -> Any: ...
    def rect2d(self, *args: Any, **kwargs: Any) -> Any: ...
    def setColor(self, *args: Any, **kwargs: Any) -> Any: ...
    def setColorIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDepthPriority(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFontIncline(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFontLine(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFontName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFontSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFontStretch(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFontWeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLineStyle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLineWidth(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPaintStyle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPointSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTexture(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTextureMask(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTextureSampler(self, *args: Any, **kwargs: Any) -> Any: ...
    def sphere(self, *args: Any, **kwargs: Any) -> Any: ...
    def text(self, *args: Any, **kwargs: Any) -> Any: ...
    def text2d(self, *args: Any, **kwargs: Any) -> Any: ...

class MUniformParameter:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def asBool(self, *args: Any, **kwargs: Any) -> Any: ...
    def asFloat(self, *args: Any, **kwargs: Any) -> Any: ...
    def asFloatArray(self, *args: Any, **kwargs: Any) -> Any: ...
    def asInt(self, *args: Any, **kwargs: Any) -> Any: ...
    def asString(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    enumFieldNames: Any = ...
    def hasChanged(self, *args: Any, **kwargs: Any) -> Any: ...
    def isATexture(self, *args: Any, **kwargs: Any) -> Any: ...
    kSemanticBackgroundColor: Any = ...
    kSemanticBump: Any = ...
    kSemanticBumpTexture: Any = ...
    kSemanticColor: Any = ...
    kSemanticColorTexture: Any = ...
    kSemanticEnvironment: Any = ...
    kSemanticFarClipPlane: Any = ...
    kSemanticFrameNumber: Any = ...
    kSemanticHWSEdgeLevel: Any = ...
    kSemanticHWSFaceLevel: Any = ...
    kSemanticHWSFrontCCW: Any = ...
    kSemanticHWSHighlighting: Any = ...
    kSemanticHWSInstancedDraw: Any = ...
    kSemanticHWSObjectLevel: Any = ...
    kSemanticHWSOccluder: Any = ...
    kSemanticHWSPrimitiveBase: Any = ...
    kSemanticHWSPrimitiveCountPerInstance: Any = ...
    kSemanticHWSVertexLevel: Any = ...
    kSemanticLocalViewer: Any = ...
    kSemanticNearClipPlane: Any = ...
    kSemanticNormal: Any = ...
    kSemanticNormalTexture: Any = ...
    kSemanticNormalizationTexture: Any = ...
    kSemanticObjectDir: Any = ...
    kSemanticObjectPos: Any = ...
    kSemanticOpaqueDepthTexture: Any = ...
    kSemanticProjectionDir: Any = ...
    kSemanticProjectionInverseMatrix: Any = ...
    kSemanticProjectionInverseTransposeMatrix: Any = ...
    kSemanticProjectionMatrix: Any = ...
    kSemanticProjectionPos: Any = ...
    kSemanticProjectionTransposeMatrix: Any = ...
    kSemanticTime: Any = ...
    kSemanticTranspDepthTexture: Any = ...
    kSemanticUnknown: Any = ...
    kSemanticViewDir: Any = ...
    kSemanticViewInverseMatrix: Any = ...
    kSemanticViewInverseTransposeMatrix: Any = ...
    kSemanticViewMatrix: Any = ...
    kSemanticViewPos: Any = ...
    kSemanticViewProjectionInverseMatrix: Any = ...
    kSemanticViewProjectionInverseTransposeMatrix: Any = ...
    kSemanticViewProjectionMatrix: Any = ...
    kSemanticViewProjectionTransposeMatrix: Any = ...
    kSemanticViewTransposeMatrix: Any = ...
    kSemanticViewportPixelSize: Any = ...
    kSemanticWorldDir: Any = ...
    kSemanticWorldInverseMatrix: Any = ...
    kSemanticWorldInverseTransposeMatrix: Any = ...
    kSemanticWorldMatrix: Any = ...
    kSemanticWorldPos: Any = ...
    kSemanticWorldTransposeMatrix: Any = ...
    kSemanticWorldViewInverseMatrix: Any = ...
    kSemanticWorldViewInverseTransposeMatrix: Any = ...
    kSemanticWorldViewMatrix: Any = ...
    kSemanticWorldViewProjectionInverseMatrix: Any = ...
    kSemanticWorldViewProjectionInverseTransposeMatrix: Any = ...
    kSemanticWorldViewProjectionMatrix: Any = ...
    kSemanticWorldViewProjectionTransposeMatrix: Any = ...
    kSemanticWorldViewTransposeMatrix: Any = ...
    kType1DTexture: Any = ...
    kType2DTexture: Any = ...
    kType3DTexture: Any = ...
    kTypeBool: Any = ...
    kTypeCubeTexture: Any = ...
    kTypeEnum: Any = ...
    kTypeEnvTexture: Any = ...
    kTypeFloat: Any = ...
    kTypeInt: Any = ...
    kTypeString: Any = ...
    kTypeUnknown: Any = ...
    keyable: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def numColumns(self, *args: Any, **kwargs: Any) -> Any: ...
    def numElements(self, *args: Any, **kwargs: Any) -> Any: ...
    def numRows(self, *args: Any, **kwargs: Any) -> Any: ...
    def plug(self, *args: Any, **kwargs: Any) -> Any: ...
    rangeMax: Any = ...
    rangeMin: Any = ...
    def semantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def setBool(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFloat(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFloatArray(self, *args: Any, **kwargs: Any) -> Any: ...
    def setInt(self, *args: Any, **kwargs: Any) -> Any: ...
    def setString(self, *args: Any, **kwargs: Any) -> Any: ...
    softRangeMax: Any = ...
    softRangeMin: Any = ...
    def source(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    uiHidden: Any = ...
    uiNiceName: Any = ...
    def userData(self, *args: Any, **kwargs: Any) -> Any: ...

class MUniformParameterList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def setElement(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLength(self, *args: Any, **kwargs: Any) -> Any: ...

class MUserRenderOperation:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    def cameraOverride(self, *args: Any, **kwargs: Any) -> Any: ...
    def enableSRGBWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUIDrawables(self, *args: Any, **kwargs: Any) -> Any: ...
    kClear: Any = ...
    kHUDRender: Any = ...
    kPresentTarget: Any = ...
    kQuadRender: Any = ...
    kSceneRender: Any = ...
    kUserDefined: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def operationType(self, *args: Any, **kwargs: Any) -> Any: ...
    def requiresLightData(self, *args: Any, **kwargs: Any) -> Any: ...
    def targetOverrideList(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewportRectangleOverride(self, *args: Any, **kwargs: Any) -> Any: ...

class MVaryingParameter:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addElement(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def destinationSetName(self, *args: Any, **kwargs: Any) -> Any: ...
    def dimension(self, *args: Any, **kwargs: Any) -> Any: ...
    def elementSize(self, *args: Any, **kwargs: Any) -> Any: ...
    def getElement(self, *args: Any, **kwargs: Any) -> Any: ...
    kBinormal: Any = ...
    kChar: Any = ...
    kColor: Any = ...
    kDouble: Any = ...
    kFloat: Any = ...
    kInt16: Any = ...
    kInt32: Any = ...
    kInvalidParameter: Any = ...
    kNoSemantic: Any = ...
    kNormal: Any = ...
    kPosition: Any = ...
    kStructure: Any = ...
    kTangent: Any = ...
    kTexCoord: Any = ...
    kUnsignedChar: Any = ...
    kUnsignedInt16: Any = ...
    kUnsignedInt32: Any = ...
    kWeight: Any = ...
    def maximumStride(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def numElements(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeElements(self, *args: Any, **kwargs: Any) -> Any: ...
    def semantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def semanticName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setSource(self, *args: Any, **kwargs: Any) -> Any: ...
    def sourceSemantic(self, *args: Any, **kwargs: Any) -> Any: ...
    def sourceSetName(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    def updateId(self, *args: Any, **kwargs: Any) -> Any: ...

class MVaryingParameterList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def setElement(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLength(self, *args: Any, **kwargs: Any) -> Any: ...

class MVertexBuffer:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def acquire(self, *args: Any, **kwargs: Any) -> Any: ...
    def commit(self, *args: Any, **kwargs: Any) -> Any: ...
    def descriptor(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasCustomResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def lockResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def map(self, *args: Any, **kwargs: Any) -> Any: ...
    def resourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def unload(self, *args: Any, **kwargs: Any) -> Any: ...
    def unlockResourceHandle(self, *args: Any, **kwargs: Any) -> Any: ...
    def unmap(self, *args: Any, **kwargs: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertexCount(self, *args: Any, **kwargs: Any) -> Any: ...

class MVertexBufferArray:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def getBuffer(self, *args: Any, **kwargs: Any) -> Any: ...
    def getName(self, *args: Any, **kwargs: Any) -> Any: ...

class MVertexBufferDescriptor:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    dataType: Any = ...
    dataTypeSize: Any = ...
    dimension: Any = ...
    name: Any = ...
    offset: Any = ...
    semantic: Any = ...
    semanticName: Any = ...
    stride: Any = ...

class MVertexBufferDescriptorList:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

key: Any = ...

maya: Any = ...

ourdict: Any = ...

py2dict: Any = ...

val: Any = ...
