"""Auto-generated stub for maya.api.OpenMayaAnim. Do not edit."""

from typing import Any

class MAnimControl:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def animationEndTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def animationStartTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def autoKeyMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def currentTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def globalInTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def globalOutTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def isPlaying(self, *args: Any, **kwargs: Any) -> Any: ...
    def isScrubbing(self, *args: Any, **kwargs: Any) -> Any: ...
    kPlaybackLoop: Any = ...
    kPlaybackOnce: Any = ...
    kPlaybackOscillate: Any = ...
    kPlaybackViewActive: Any = ...
    kPlaybackViewAll: Any = ...
    def maxTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def minTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def playBackward(self, *args: Any, **kwargs: Any) -> Any: ...
    def playForward(self, *args: Any, **kwargs: Any) -> Any: ...
    def playbackBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def playbackMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def playbackSpeed(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimationEndTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimationStartEndTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimationStartTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAutoKeyMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setCurrentTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGlobalInTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setGlobalOutTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMaxTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinMaxTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setMinTime(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPlaybackBy(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPlaybackMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPlaybackSpeed(self, *args: Any, **kwargs: Any) -> Any: ...
    def setViewMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeightedTangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self, *args: Any, **kwargs: Any) -> Any: ...
    def viewMode(self, *args: Any, **kwargs: Any) -> Any: ...
    def weightedTangents(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimCurveChange:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def redoIt(self, *args: Any, **kwargs: Any) -> Any: ...
    def undoIt(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimCurveClipboard:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def clipboardItems(self, *args: Any, **kwargs: Any) -> Any: ...
    endTime: Any = ...
    endUnitlessInput: Any = ...
    isEmpty: Any = ...
    def set(self, *args: Any, **kwargs: Any) -> Any: ...
    startTime: Any = ...
    startUnitlessInput: Any = ...
    theAPIClipboard: Any = ...

class MAnimCurveClipboardItem:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    animCurve: Any = ...
    def animCurveType(self, *args: Any, **kwargs: Any) -> Any: ...
    fullAttributeName: Any = ...
    def getAddressingInfo(self, *args: Any, **kwargs: Any) -> Any: ...
    leafAttributeName: Any = ...
    nodeName: Any = ...
    def setAddressingInfo(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAnimCurve(self, *args: Any, **kwargs: Any) -> Any: ...
    def setNameInfo(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimCurveClipboardItemArray:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...
    def setLength(self, *args: Any, **kwargs: Any) -> Any: ...
    sizeIncrement: Any = ...

class MAnimMessage:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAnimCurveEditedCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAnimKeyframeEditCheckCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAnimKeyframeEditedCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addDisableImplicitControlCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addNodeAnimKeyframeEditedCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addPostBakeResultsCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def addPreBakeResultsCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def currentCallbackId(self, *args: Any, **kwargs: Any) -> Any: ...
    def flushAnimKeyframeEditedCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    kDefaultAction: Any = ...
    kDoAction: Any = ...
    kDoNotDoAction: Any = ...
    def nodeCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeCallback(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...

class MAnimUtil:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimatablePlugs(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimatedPlugs(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def findConstraint(self, *args: Any, **kwargs: Any) -> Any: ...
    def findSetDrivenKeyAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def isAnimated(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnAnimCurve:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def addKey(self, *args: Any, **kwargs: Any) -> Any: ...
    def addKeys(self, *args: Any, **kwargs: Any) -> Any: ...
    def addKeysWithTangents(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    animCurveType: Any = ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    def evaluate(self, *args: Any, **kwargs: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findClosest(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTangentAngleWeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def getTangentXY(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def inTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def input(self, *args: Any, **kwargs: Any) -> Any: ...
    def insertKey(self, *args: Any, **kwargs: Any) -> Any: ...
    def isBreakdown(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    isStatic: Any = ...
    isTimeInput: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    isUnitlessInput: Any = ...
    isWeighted: Any = ...
    kAnimCurveTA: Any = ...
    kAnimCurveTL: Any = ...
    kAnimCurveTT: Any = ...
    kAnimCurveTU: Any = ...
    kAnimCurveUA: Any = ...
    kAnimCurveUL: Any = ...
    kAnimCurveUT: Any = ...
    kAnimCurveUU: Any = ...
    kAnimCurveUnknown: Any = ...
    kConstant: Any = ...
    kCycle: Any = ...
    kCycleRelative: Any = ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLinear: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kOscillate: Any = ...
    kTangentAuto: Any = ...
    kTangentAutoCustom: Any = ...
    kTangentAutoEase: Any = ...
    kTangentAutoMix: Any = ...
    kTangentClamped: Any = ...
    kTangentCustomEnd: Any = ...
    kTangentCustomStart: Any = ...
    kTangentFast: Any = ...
    kTangentFixed: Any = ...
    kTangentFlat: Any = ...
    kTangentGlobal: Any = ...
    kTangentLinear: Any = ...
    kTangentPlateau: Any = ...
    kTangentShared1: Any = ...
    kTangentShared2: Any = ...
    kTangentShared3: Any = ...
    kTangentShared4: Any = ...
    kTangentShared5: Any = ...
    kTangentShared6: Any = ...
    kTangentShared7: Any = ...
    kTangentShared8: Any = ...
    kTangentSlow: Any = ...
    kTangentSmooth: Any = ...
    kTangentStep: Any = ...
    kTangentStepNext: Any = ...
    kTangentTypeCount: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    numKeys: Any = ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    postInfinityType: Any = ...
    preInfinityType: Any = ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAngle(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setInTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setInput(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIsBreakdown(self, *args: Any, **kwargs: Any) -> Any: ...
    def setIsWeighted(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setOutTangentType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPostInfinityType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setPreInfinityType(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTangent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTangentTypes(self, *args: Any, **kwargs: Any) -> Any: ...
    def setTangentsLocked(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def setValue(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeight(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeightsLocked(self, *args: Any, **kwargs: Any) -> Any: ...
    def tangentsLocked(self, *args: Any, **kwargs: Any) -> Any: ...
    def timedAnimCurveTypeForPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def unitlessAnimCurveTypeForPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def value(self, *args: Any, **kwargs: Any) -> Any: ...
    def weightsLocked(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnGeometryFilter:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    deformerSet: Any = ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    envelope: Any = ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getComponentAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getInputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getOutputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPathAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def groupIdAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForGroupId(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputShape(self, *args: Any, **kwargs: Any) -> Any: ...
    def inputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    def numOutputConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...

class MFnSkinCluster:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def absoluteName(self, *args: Any, **kwargs: Any) -> Any: ...
    def addAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def addExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def affectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def allocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeClass(self, *args: Any, **kwargs: Any) -> Any: ...
    def attributeCount(self, *args: Any, **kwargs: Any) -> Any: ...
    def canBeWritten(self, *args: Any, **kwargs: Any) -> Any: ...
    def classification(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateAllFlags(self, *args: Any, **kwargs: Any) -> Any: ...
    def deallocateFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    deformerSet: Any = ...
    def dgCallbackIds(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgCallbacks(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimer(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOff(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerOn(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerQueryState(self, *args: Any, **kwargs: Any) -> Any: ...
    def dgTimerReset(self, *args: Any, **kwargs: Any) -> Any: ...
    envelope: Any = ...
    def findAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def findPlug(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectedAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAffectingAttributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def getAliasList(self, *args: Any, **kwargs: Any) -> Any: ...
    def getBlendWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def getComponentAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def getExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def getInputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getOutputGeometry(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPathAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def getPointsAffectedByInfluence(self, *args: Any, **kwargs: Any) -> Any: ...
    def getWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def groupIdAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasObj(self, *args: Any, **kwargs: Any) -> Any: ...
    def hasUniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForGroupId(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForInfluenceObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputConnection(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexForOutputShape(self, *args: Any, **kwargs: Any) -> Any: ...
    def influenceObjects(self, *args: Any, **kwargs: Any) -> Any: ...
    def inputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    isDefaultNode: Any = ...
    def isFlagSet(self, *args: Any, **kwargs: Any) -> Any: ...
    isFromReferencedFile: Any = ...
    isLocked: Any = ...
    def isNewAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    isShared: Any = ...
    def isTrackingEdits(self, *args: Any, **kwargs: Any) -> Any: ...
    kExtensionAttr: Any = ...
    kInvalidAttr: Any = ...
    kLocalDynamicAttr: Any = ...
    kNormalAttr: Any = ...
    kTimerInvalidState: Any = ...
    kTimerMetric_callback: Any = ...
    kTimerMetric_callbackNotViaAPI: Any = ...
    kTimerMetric_callbackViaAPI: Any = ...
    kTimerMetric_compute: Any = ...
    kTimerMetric_computeDuringCallback: Any = ...
    kTimerMetric_computeNotDuringCallback: Any = ...
    kTimerMetric_dirty: Any = ...
    kTimerMetric_draw: Any = ...
    kTimerMetric_fetch: Any = ...
    kTimerMetrics: Any = ...
    kTimerOff: Any = ...
    kTimerOn: Any = ...
    kTimerType_count: Any = ...
    kTimerType_inclusive: Any = ...
    kTimerType_self: Any = ...
    kTimerTypes: Any = ...
    kTimerUninitialized: Any = ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    namespace: Any = ...
    def numOutputConnections(self, *args: Any, **kwargs: Any) -> Any: ...
    def object(self, *args: Any, **kwargs: Any) -> Any: ...
    def outputShapeAtIndex(self, *args: Any, **kwargs: Any) -> Any: ...
    pluginName: Any = ...
    def plugsAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def removeAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def reorderedAttribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAffectsAnimation(self, *args: Any, **kwargs: Any) -> Any: ...
    def setAlias(self, *args: Any, **kwargs: Any) -> Any: ...
    def setBlendWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def setDoNotWrite(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContent(self, *args: Any, **kwargs: Any) -> Any: ...
    def setExternalContentForFileAttr(self, *args: Any, **kwargs: Any) -> Any: ...
    def setFlag(self, *args: Any, **kwargs: Any) -> Any: ...
    def setName(self, *args: Any, **kwargs: Any) -> Any: ...
    def setObject(self, *args: Any, **kwargs: Any) -> Any: ...
    def setUuid(self, *args: Any, **kwargs: Any) -> Any: ...
    def setWeights(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...
    typeId: Any = ...
    typeName: Any = ...
    def uniqueName(self, *args: Any, **kwargs: Any) -> Any: ...
    def userNode(self, *args: Any, **kwargs: Any) -> Any: ...
    def uuid(self, *args: Any, **kwargs: Any) -> Any: ...

key: Any = ...

maya: Any = ...

ourdict: Any = ...

py2dict: Any = ...

val: Any = ...
